In [1]:
import findspark
findspark.init()
import pyspark
from pyspark.sql import SparkSession
import os
os.chdir('/home/xiaoyusun')
spark=SparkSession.builder.master('spark://LAPTOP-7D78FTBR.localdomain:7077').appName('DataFrame-Spark').getOrCreate()

23/06/02 10:48:47 WARN Utils: Your hostname, LAPTOP-7D78FTBR resolves to a loopback address: 127.0.1.1; using 172.24.204.163 instead (on interface eth0)
23/06/02 10:48:47 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/xiaoyusun/spark3.2/jars/spark-unsafe_2.12-3.2.4.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
23/06/02 10:48:49 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

In [4]:
df = spark.read.csv('data.CSV')
df.show(5)
df.printSchema()

+--------------------+---+--------------------+------------+--------+-----+----------+----------+
|                 _c0|_c1|                 _c2|         _c3|     _c4|  _c5|       _c6|       _c7|
+--------------------+---+--------------------+------------+--------+-----+----------+----------+
|                name|age|              street|        city|   state|  zip|       lng|       lat|
|       Shirley Green| 51|503 Davis Tunnel ...|   Port Ruth|   Idaho|92155|127.435760|-9.8076355|
|Christopher Williams| 50|1267 Mary Tunnel ...|  Port Shane|Delaware|15896| 32.903300|-21.212263|
|         Vicki Brown| 75|94223 Patricia St...|Schwartzside|  Oregon|64721| 62.898116|34.7408695|
|      Douglas Snyder| 23|8307 Cindy Field ...|  Ashleyberg|    Iowa|57094|151.321619| -7.139480|
+--------------------+---+--------------------+------------+--------+-----+----------+----------+
only showing top 5 rows

root
 |-- _c0: string (nullable = true)
 |-- _c1: string (nullable = true)
 |-- _c2: string (nullable = true)
 |-- _c3: string (nullable = true)
 |-- _c4: string (nullable = true)
 |-- _c5: string (nullable = true)
 |-- _c6: string (nullable = true)
 |-- _c7: string (nullable = true)

In [6]:
df = spark.read.csv('data.CSV',header=True,inferSchema=True)
df.show(5)

+--------------------+---+--------------------+------------+--------+-----+----------+----------+
|                name|age|              street|        city|   state|  zip|       lng|       lat|
+--------------------+---+--------------------+------------+--------+-----+----------+----------+
|       Shirley Green| 51|503 Davis Tunnel ...|   Port Ruth|   Idaho|92155| 127.43576|-9.8076355|
|Christopher Williams| 50|1267 Mary Tunnel ...|  Port Shane|Delaware|15896|   32.9033|-21.212263|
|         Vicki Brown| 75|94223 Patricia St...|Schwartzside|  Oregon|64721| 62.898116|34.7408695|
|      Douglas Snyder| 23|8307 Cindy Field ...|  Ashleyberg|    Iowa|57094|151.321619|  -7.13948|
|        Rebecca Neal| 73|733 Allison Junct...|    Reedstad|    Utah|94289|163.616939|83.8663655|
+--------------------+---+--------------------+------------+--------+-----+----------+----------+
only showing top 5 rows

In [7]:
df.select('name').show()

+--------------------+
|                name|
+--------------------+
|       Shirley Green|
|Christopher Williams|
|         Vicki Brown|
|      Douglas Snyder|
|        Rebecca Neal|
|       Sharon Martin|
|        Travis Davis|
|      Jessica Miller|
|        Colin Carter|
|      Gary Castaneda|
|        David Morrow|
|       Kara Sandoval|
|       Nicole Ingram|
|       Eric Franklin|
|       Steven Bolton|
|       Dennis Howard|
|       Monica Bailey|
|   Christopher Avery|
|         Jose Acosta|
|          David Yang|
+--------------------+
only showing top 20 rows

In [8]:
df.select(df['age']<40).show()# Select return show or false

+----------+
|(age < 40)|
+----------+
|     false|
|     false|
|     false|
|      true|
|     false|
|     false|
|      true|
|     false|
|      true|
|     false|
|     false|
|      true|
|     false|
|      true|
|      true|
|     false|
|     false|
|     false|
|      true|
|     false|
+----------+
only showing top 20 rows

In [9]:
df.filter(df['age']<40).show()#filter return data

+--------------------+---+--------------------+--------------------+--------------+-----+-----------+-----------+
|                name|age|              street|                city|         state|  zip|        lng|        lat|
+--------------------+---+--------------------+--------------------+--------------+-----+-----------+-----------+
|      Douglas Snyder| 23|8307 Cindy Field ...|          Ashleyberg|          Iowa|57094| 151.321619|   -7.13948|
|        Travis Davis| 25| 1496 Perez Junction|        Lake Melinda|          Utah|31874| 129.198262| -86.722102|
|        Colin Carter| 34|    534 Marshall Way|      Port Calebbury|         Maine|25208|  46.737898|  80.764342|
|       Kara Sandoval| 30|  831 Amber Crescent|         Cynthiatown|South Carolina|65868| 120.819117| 45.1953135|
|       Eric Franklin| 33|   7118 Goodman Mall|      North Kathleen|North Carolina|92272|  93.319131|-49.2371385|
|       Steven Bolton| 27|6644 Brian Flat S...|North Jeffreychester|North Carolina|69441|  -75.89488|-38.8799715|
|         Jose Acosta| 34|708 Tonya Forges ...|          New Amanda|     Wisconsin|84664| 147.080022| 71.8281255|
|      Mallory Newton| 38|675 Rogers Road S...|      Shannonchester|        Hawaii|10481|-157.341507| -88.335825|
|   Mr. Richard Moore| 39|  412 Fowler Islands|    Christopherville|       Vermont|22199| -75.610711|-39.8949425|
|          William Li| 30|4431 Robert Rue S...|           Lanceberg|       Alabama|14598|-159.934529|-46.5291295|
|     Karen Carpenter| 39|  102 Michelle Ports|   New Mercedesmouth|     Louisiana|15374| -31.647568| -63.178956|
|         Jacob Marsh| 29| 44972 Lawrence Cove|         Bowmanmouth|    Washington|27731|   65.88709| -54.608903|
|         John Parker| 33|9979 Ronald Freew...|        Lake Michael|    New Mexico|49965|  77.921187| 17.5216885|
|         Kelly White| 34|475 Kirk Lock Apt...|   Port Richardville|       Georgia|32450|  97.258658|-74.9886005|
|Alexandra Mullins...| 32| 7330 Randall Island|          Kaylashire|       Georgia|46653| 109.190572|  11.748215|
|Ms. Nicole Henderson| 36|1500 Brittney Ave...|           New Jesus|      Missouri| 2841|-128.868462|-75.9054695|
|      Richard Murray| 24|023 Gomez Circle ...|             Codyton|      Illinois|29510|  -48.65468|  24.241075|
|        Stacy Wilson| 25|2594 Gilmore Cour...|            Donnaton| New Hampshire|52778|-125.802769| -66.120617|
|       Stephen Moore| 18|062 Snyder Dale A...|         Taylorshire|South Carolina|79283| 121.001126| 21.2042355|
|      Michael Palmer| 20|05907 White Commo...|          Port Megan| West Virginia|99181| -98.107018| -14.371527|
+--------------------+---+--------------------+--------------------+--------------+-----+-----------+-----------+
only showing top 20 rows

In [10]:
df.filter('age<40').select(['name','age','state']).show()

+--------------------+---+--------------+
|                name|age|         state|
+--------------------+---+--------------+
|      Douglas Snyder| 23|          Iowa|
|        Travis Davis| 25|          Utah|
|        Colin Carter| 34|         Maine|
|       Kara Sandoval| 30|South Carolina|
|       Eric Franklin| 33|North Carolina|
|       Steven Bolton| 27|North Carolina|
|         Jose Acosta| 34|     Wisconsin|
|      Mallory Newton| 38|        Hawaii|
|   Mr. Richard Moore| 39|       Vermont|
|          William Li| 30|       Alabama|
|     Karen Carpenter| 39|     Louisiana|
|         Jacob Marsh| 29|    Washington|
|         John Parker| 33|    New Mexico|
|         Kelly White| 34|       Georgia|
|Alexandra Mullins...| 32|       Georgia|
|Ms. Nicole Henderson| 36|      Missouri|
|      Richard Murray| 24|      Illinois|
|        Stacy Wilson| 25| New Hampshire|
|       Stephen Moore| 18|South Carolina|
|      Michael Palmer| 20| West Virginia|
+--------------------+---+--------------+
only showing top 20 rows

In [11]:
u40=df.filter('age<40').collect()# create an array of rows
u40

[Row(name='Douglas Snyder', age=23, street='8307 Cindy Field Apt. 585', city='Ashleyberg', state='Iowa', zip=57094, lng=151.321619, lat=-7.13948),
 Row(name='Travis Davis', age=25, street='1496 Perez Junction', city='Lake Melinda', state='Utah', zip=31874, lng=129.198262, lat=-86.722102),
 Row(name='Colin Carter', age=34, street='534 Marshall Way', city='Port Calebbury', state='Maine', zip=25208, lng=46.737898, lat=80.764342),
 Row(name='Kara Sandoval', age=30, street='831 Amber Crescent', city='Cynthiatown', state='South Carolina', zip=65868, lng=120.819117, lat=45.1953135),
 Row(name='Eric Franklin', age=33, street='7118 Goodman Mall', city='North Kathleen', state='North Carolina', zip=92272, lng=93.319131, lat=-49.2371385),
 Row(name='Steven Bolton', age=27, street='6644 Brian Flat Suite 460', city='North Jeffreychester', state='North Carolina', zip=69441, lng=-75.89488, lat=-38.8799715),
 Row(name='Jose Acosta', age=34, street='708 Tonya Forges Apt. 669', city='New Amanda', state='Wisconsin', zip=84664, lng=147.080022, lat=71.8281255),
 Row(name='Mallory Newton', age=38, street='675 Rogers Road Suite 447', city='Shannonchester', state='Hawaii', zip=10481, lng=-157.341507, lat=-88.335825),
 Row(name='Mr. Richard Moore', age=39, street='412 Fowler Islands', city='Christopherville', state='Vermont', zip=22199, lng=-75.610711, lat=-39.8949425),
 Row(name='William Li', age=30, street='4431 Robert Rue Suite 911', city='Lanceberg', state='Alabama', zip=14598, lng=-159.934529, lat=-46.5291295),
 Row(name='Karen Carpenter', age=39, street='102 Michelle Ports', city='New Mercedesmouth', state='Louisiana', zip=15374, lng=-31.647568, lat=-63.178956),
 Row(name='Jacob Marsh', age=29, street='44972 Lawrence Cove', city='Bowmanmouth', state='Washington', zip=27731, lng=65.88709, lat=-54.608903),
 Row(name='John Parker', age=33, street='9979 Ronald Freeway Apt. 705', city='Lake Michael', state='New Mexico', zip=49965, lng=77.921187, lat=17.5216885),
 Row(name='Kelly White', age=34, street='475 Kirk Lock Apt. 449', city='Port Richardville', state='Georgia', zip=32450, lng=97.258658, lat=-74.9886005),
 Row(name='Alexandra Mullins DDS', age=32, street='7330 Randall Island', city='Kaylashire', state='Georgia', zip=46653, lng=109.190572, lat=11.748215),
 Row(name='Ms. Nicole Henderson', age=36, street='1500 Brittney Avenue Apt. 743', city='New Jesus', state='Missouri', zip=2841, lng=-128.868462, lat=-75.9054695),
 Row(name='Richard Murray', age=24, street='023 Gomez Circle Suite 891', city='Codyton', state='Illinois', zip=29510, lng=-48.65468, lat=24.241075),
 Row(name='Stacy Wilson', age=25, street='2594 Gilmore Court Apt. 716', city='Donnaton', state='New Hampshire', zip=52778, lng=-125.802769, lat=-66.120617),
 Row(name='Stephen Moore', age=18, street='062 Snyder Dale Apt. 396', city='Taylorshire', state='South Carolina', zip=79283, lng=121.001126, lat=21.2042355),
 Row(name='Michael Palmer', age=20, street='05907 White Common Apt. 437', city='Port Megan', state='West Virginia', zip=99181, lng=-98.107018, lat=-14.371527),
 Row(name='Alyssa Burgess', age=28, street='44467 Torres Ridge Apt. 767', city='Spencerburgh', state='Maryland', zip=85793, lng=105.219483, lat=18.693497),
 Row(name='Ronald Green', age=32, street='15655 Hernandez Mill Suite 837', city='Port Phyllis', state='California', zip=26342, lng=-160.527931, lat=39.48574),
 Row(name='Jason Baker', age=33, street='9204 Kylie View Suite 653', city='Abigailburgh', state='Iowa', zip=7917, lng=-142.496693, lat=-36.58947),
 Row(name='Margaret Griffith', age=23, street='69635 Palmer Trail Suite 465', city='Port Alyssa', state='Colorado', zip=29424, lng=115.167632, lat=57.034145),
 Row(name='Brandon Valencia', age=35, street='5820 Tammy Track Suite 560', city='North Allison', state='Oklahoma', zip=43571, lng=-158.450745, lat=-10.753513),
 Row(name='Mr. Adam Smith', age=38, street='299 Blankenship Land Apt. 345', city='Seanview', state='Montana', zip=74018, lng=-53.624781, lat=-77.935335),
 Row(name='John Rodgers', age=18, street='3495 Gloria Ferry', city='Pattersonhaven', state='New Mexico', zip=46820, lng=-32.488061, lat=83.2514325),
 Row(name='Lee Donaldson', age=23, street='737 Micheal Junction', city='Susanmouth', state='Vermont', zip=9211, lng=-14.178351, lat=-10.378729),
 Row(name='Robert Sharp', age=34, street='65205 Dennis Crescent Apt. 585', city='Lake Wendytown', state='Georgia', zip=24348, lng=-74.568626, lat=17.443412),
 Row(name='Cole Fletcher', age=31, street='96385 Diaz Underpass', city='Shieldston', state='North Carolina', zip=98083, lng=-74.320038, lat=55.7360175),
 Row(name='Nicholas Carlson', age=29, street='53642 Jacqueline Trail Suite 843', city='North Sandraburgh', state='North Dakota', zip=21062, lng=173.932076, lat=55.0328045),
 Row(name='Jesse Mcgee', age=26, street='0266 Chan Street Suite 332', city='North Robert', state='Maryland', zip=1640, lng=117.483637, lat=68.888271),
 Row(name='Melissa Clark', age=34, street='963 Huber Mountain Apt. 473', city='New Marytown', state='Nevada', zip=57592, lng=166.489018, lat=-59.325578),
 Row(name='Kimberly Martin', age=20, street='27881 Kenneth Locks', city='Orozcotown', state='Wisconsin', zip=33665, lng=-31.494113, lat=12.952741),
 Row(name='Jennifer Austin', age=39, street='2246 Klein Ports Suite 721', city='Trevorport', state='Arkansas', zip=24865, lng=-73.040314, lat=17.664625),
 Row(name='Mrs. Marissa Massey', age=32, street='84612 Pamela Extension', city='North Kelseyburgh', state='North Carolina', zip=13310, lng=-77.854326, lat=48.8903585),
 Row(name='Michelle Hernandez', age=20, street='9107 Carlos Fall Suite 838', city='Marioland', state='Virginia', zip=23615, lng=-51.187402, lat=7.6954185),
 Row(name='Charles Ramirez', age=25, street='9224 Vasquez Branch Apt. 766', city='New Scott', state='Kentucky', zip=85964, lng=-69.383591, lat=85.736318),
 Row(name='Jacqueline Tucker', age=26, street='9726 Castro Road', city='North Jenniferland', state='Rhode Island', zip=86491, lng=48.97366, lat=7.4428555),
 Row(name='Vincent Woodard', age=27, street='063 Perkins Valley', city='West Joshua', state='Ohio', zip=94391, lng=124.887258, lat=-4.6209475),
 Row(name='Lisa Norman', age=21, street='46237 Christopher Rest', city='New Ralph', state='Tennessee', zip=6051, lng=-87.514312, lat=-46.368582),
 Row(name='Anthony Johnson', age=35, street='2689 Pham Crest', city='Port Johnathan', state='South Carolina', zip=37154, lng=65.564821, lat=-30.556331),
 Row(name='Donna Mccullough', age=18, street='8004 Watson Shores Apt. 537', city='Joshuafurt', state='Hawaii', zip=2350, lng=-171.521481, lat=34.34947),
 Row(name='Rachel Mitchell', age=26, street='34878 Campbell Mission Apt. 541', city='East Michelle', state='Oklahoma', zip=14410, lng=-65.802526, lat=20.9933865),
 Row(name='Erica Houston DDS', age=28, street='79314 Todd Trace', city='South Joseph', state='California', zip=14643, lng=-124.875787, lat=-24.3770745),
 Row(name='Daniel Erickson', age=36, street='628 Dawn Loop Apt. 327', city='Lake Rebeccatown', state='Wisconsin', zip=67493, lng=164.358257, lat=-13.256061),
 Row(name='Amber Hill DDS', age=37, street='26874 Shaffer River Apt. 548', city='South Marciamouth', state='Illinois', zip=65406, lng=-67.917689, lat=54.354821),
 Row(name='Andrea Bray', age=18, street='405 Michael Junction', city='Port Hollytown', state='Nebraska', zip=37708, lng=-146.141492, lat=-71.2758245),
 Row(name='Kristen Rivera', age=38, street='763 Miller Bypass', city='North Tiffany', state='South Dakota', zip=93706, lng=172.739307, lat=-80.1932545),
 Row(name='Carol Perez', age=30, street='0443 Linda Village', city='Rossport', state='Missouri', zip=16757, lng=-139.921034, lat=53.237987),
 Row(name='David Moore', age=19, street='1469 Benjamin Mall', city='Tiffanyborough', state='Wyoming', zip=23157, lng=-61.576129, lat=11.5425515),
 Row(name='David Harrison', age=36, street='5175 Katherine Wells Apt. 635', city='North Curtischester', state='Alaska', zip=93265, lng=-23.320422, lat=72.2174435),
 Row(name='Frederick Evans', age=33, street='58368 Caleb Camp', city='Penningtonburgh', state='Louisiana', zip=53793, lng=-173.223589, lat=83.034729),
 Row(name='Denise Rush', age=21, street='122 Jones Islands Apt. 136', city='Amyton', state='Alaska', zip=24856, lng=173.722498, lat=-26.9038975),
 Row(name='Traci Gallagher', age=20, street='93101 Bennett Lake Apt. 438', city='New Ericashire', state='Arkansas', zip=31040, lng=-118.69654, lat=73.6021305),
 Row(name='Justin Page', age=19, street='7874 Sarah Manors Suite 460', city='New Peterside', state='California', zip=24606, lng=-11.110459, lat=52.4860345),
 Row(name='Arthur Stone', age=18, street='00411 Jones Island Apt. 757', city='West Sydney', state='West Virginia', zip=51328, lng=136.728678, lat=83.680243),
 Row(name='Cindy Williams', age=18, street='617 Ross Shoal', city='Port Michael', state='Hawaii', zip=64836, lng=83.974455, lat=87.5228595),
 Row(name='Larry Dunn', age=30, street='377 Shawn Well', city='Lake Kellyville', state='Texas', zip=21402, lng=64.215362, lat=-24.93869),
 Row(name='Richard Howell', age=26, street='7431 Victor Stream', city='Allisonbury', state='Alaska', zip=23534, lng=-53.108344, lat=-69.0272895),
 Row(name='Stephen Owens', age=39, street='8515 Susan Lights Apt. 535', city='Jonathanmouth', state='New Mexico', zip=8499, lng=123.350351, lat=45.8033095),
 Row(name='Emily Mccarthy', age=20, street='568 Kayla Centers', city='Port Edwardville', state='New Mexico', zip=83038, lng=141.295739, lat=72.147992),
 Row(name='Jacqueline Hawkins', age=33, street='5857 Hood Lake Apt. 485', city='Lake Cynthia', state='Mississippi', zip=38079, lng=22.381065, lat=56.43137),
 Row(name='David Solomon', age=38, street='869 Bradley Bypass Suite 753', city='Webbfort', state='Maryland', zip=67278, lng=52.976344, lat=20.546445),
 Row(name='Mrs. Rebecca Rowe', age=39, street='067 Michaela Forks Apt. 197', city='Angelicaport', state='Michigan', zip=83538, lng=-153.750449, lat=69.866695),
 Row(name='David Thompson', age=26, street='159 Clay Fork', city='Richardston', state='Illinois', zip=43916, lng=45.284211, lat=50.87704),
 Row(name='John Cole', age=34, street='16998 Jamie Keys', city='Port Stacy', state='Colorado', zip=3433, lng=155.816205, lat=-51.92454),
 Row(name='Cathy Thompson', age=29, street='9667 Potts Island', city='New David', state='Missouri', zip=2381, lng=80.516942, lat=67.379554),
 Row(name='Sonya English', age=34, street='969 Kevin Circles Apt. 205', city='South Robert', state='Wisconsin', zip=69758, lng=124.837828, lat=-61.301577),
 Row(name='Bryan Perez', age=34, street='27873 Dana Greens', city='Bellbury', state='Oklahoma', zip=72395, lng=176.590107, lat=26.8938065),
 Row(name='Jeremy Steele', age=33, street='590 Ricardo Island', city='Gallegosborough', state='West Virginia', zip=95613, lng=73.065022, lat=-60.9064405),
 Row(name='Mark Alexander', age=23, street='7036 Michelle Curve', city='Perryside', state='Massachusetts', zip=81469, lng=-116.947192, lat=-4.943737),
 Row(name='Zachary Smith', age=36, street='55085 Victoria Parkway Suite 952', city='North Christopher', state='Alabama', zip=41646, lng=171.419597, lat=74.2019395),
 Row(name='Shelly Arias', age=29, street='811 Emily Rapid Apt. 406', city='Nealstad', state='California', zip=37873, lng=-140.776914, lat=-86.946908),
 Row(name='Juan Wood', age=20, street='6185 Ortiz Plains', city='South Melvinside', state='Alaska', zip=13616, lng=90.614015, lat=74.3701815),
 Row(name='Susan Hansen', age=26, street='391 Carpenter Freeway Apt. 191', city='Collierfort', state='Tennessee', zip=48700, lng=-104.567852, lat=-25.031846),
 Row(name='Marcus Fitzgerald', age=39, street='3262 Kim Lodge Suite 869', city='Derekberg', state='Vermont', zip=18365, lng=88.238182, lat=-67.1448145),
 Row(name='Brent Woodward', age=23, street='93383 Thomas Dam Apt. 542', city='Port Robertfort', state='Louisiana', zip=9333, lng=45.532305, lat=78.2564305),
 Row(name='Perry Paul', age=26, street='87407 Ramos Creek', city='Molinabury', state='Montana', zip=44713, lng=-34.865722, lat=70.2174135),
 Row(name='James Guzman', age=22, street='63389 Mary Street Suite 143', city='Lambland', state='Maryland', zip=85589, lng=-107.80104, lat=46.662965),
 Row(name='Lawrence Abbott', age=39, street='835 Coleman Cape Suite 714', city='New Markland', state='Kentucky', zip=59334, lng=108.385342, lat=-10.970527),
 Row(name='James Barrett', age=24, street='6993 Timothy Drive', city='Wilsonberg', state='Florida', zip=3823, lng=-166.90839, lat=-16.334232),
 Row(name='Alexandra Horne', age=25, street='479 Richardson Trace', city='Ryanfort', state='Connecticut', zip=83665, lng=-41.436271, lat=-63.6067135),
 Row(name='Tina Cooper', age=18, street='38458 Patricia Way', city='Bradyville', state='Washington', zip=42539, lng=-14.231671, lat=32.180067),
 Row(name='Karina Boyd', age=22, street='84497 Paul Pine', city='East Andreaport', state='Colorado', zip=66533, lng=-157.230803, lat=-11.5398545),
 Row(name='Kim Rogers', age=26, street='013 Evans Pine', city='Mitchellfort', state='Nevada', zip=37860, lng=91.765368, lat=5.340507),
 Row(name='Katherine Schmidt', age=30, street='67745 Anthony Creek', city='Nataliehaven', state='Utah', zip=36188, lng=-113.26994, lat=23.8302845),
 Row(name='Richard Smith', age=20, street='217 Sabrina Track Apt. 403', city='Wolfeville', state='Iowa', zip=50486, lng=-167.228525, lat=46.4579265),
 Row(name='Robert Mccullough', age=33, street='2478 Rickey Union', city='Hermanport', state='Pennsylvania', zip=14152, lng=103.804379, lat=56.1258335),
 Row(name='Michael Neal', age=22, street='9362 Megan Lakes Apt. 418', city='South Marilynland', state='Oklahoma', zip=50168, lng=111.584163, lat=67.2212765),
 Row(name='Elizabeth Sanchez', age=39, street='099 Mendoza Mills', city='Riveraport', state='Wisconsin', zip=96856, lng=-112.351885, lat=8.937676),
 Row(name='Walter Greer', age=37, street='647 Ochoa Mission', city='Juliahaven', state='Delaware', zip=11692, lng=-119.53241, lat=26.915679),
 Row(name='Mercedes Jones', age=27, street='2297 Ronald Crescent Suite 276', city='Snyderchester', state='Oklahoma', zip=12181, lng=-40.37932, lat=-58.4787745),
 Row(name='Thomas Thomas', age=34, street='69009 Adam Glen Apt. 737', city='Allisonside', state='New Jersey', zip=53476, lng=-54.341757, lat=-35.3304985),
 Row(name='Mike Dixon', age=39, street='400 Jones Forest', city='Rogersview', state='Tennessee', zip=69386, lng=68.244285, lat=85.38242),
 Row(name='Bethany Lee', age=25, street='559 Henderson Mill', city='West Chelseaton', state='Pennsylvania', zip=88696, lng=-145.706621, lat=7.5191705),
 Row(name='Carlos Delgado', age=21, street='04867 Debra Street', city='West Michaelport', state='Montana', zip=8910, lng=-122.031591, lat=-36.7863435),
 Row(name='Rhonda Solis', age=35, street='942 Kevin River', city='Walkerport', state='Nevada', zip=6147, lng=-101.42165, lat=55.5016285),
 Row(name='Michael Jordan', age=24, street='095 Max Trail Suite 148', city='New Susan', state='West Virginia', zip=91942, lng=35.572501, lat=67.857958),
 Row(name='Tonya Glenn', age=32, street='9286 Michael Pine', city='East Jeffreystad', state='Tennessee', zip=90783, lng=-57.184689, lat=87.3673585),
 Row(name='Kevin Miller', age=22, street='273 Russell Mountains', city='Port Heather', state='Hawaii', zip=35951, lng=109.519506, lat=69.138615),
 Row(name='Adam Beard', age=21, street='172 Jessica Lake', city='Huberberg', state='Arizona', zip=93042, lng=120.247073, lat=66.5133075),
 Row(name='Patrick Carpenter', age=39, street='235 Smith Tunnel Apt. 299', city='Davidbury', state='Arizona', zip=38348, lng=78.867817, lat=-79.825791),
 Row(name='William Baker', age=36, street='82108 Cruz Shores', city='South John', state='Pennsylvania', zip=84689, lng=-58.233419, lat=-56.4814765),
 Row(name='Kristin Hughes', age=28, street='0890 Reed Greens', city='New Lisahaven', state='Nebraska', zip=40363, lng=172.682015, lat=37.2529735),
 Row(name='Mary Flowers', age=34, street='4731 Cody Lodge Apt. 606', city='South David', state='Mississippi', zip=14479, lng=-172.794529, lat=-73.2650515),
 Row(name='Linda Brown', age=22, street='866 Michael Crescent Apt. 954', city='Port Adamburgh', state='Idaho', zip=38085, lng=176.30213, lat=45.03062),
 Row(name='Nichole Castro', age=32, street='549 Edwin Freeway Apt. 428', city='Lake Raymond', state='Pennsylvania', zip=13092, lng=-27.34863, lat=-45.054988),
 Row(name='Leslie Dean', age=35, street='44704 Spencer Mountains Suite 552', city='Alanport', state='Kansas', zip=99766, lng=66.853626, lat=-84.06461),
 Row(name='Benjamin Navarro', age=25, street='8812 Matthew Summit Apt. 354', city='Barronfort', state='Nevada', zip=30302, lng=-158.432998, lat=35.821897),
 Row(name='Kathy Goodman', age=33, street='402 Jonathan Lakes Suite 362', city='Jacksonshire', state='Florida', zip=28313, lng=-23.93757, lat=-35.6394615),
 Row(name='Chelsea Jensen', age=22, street='218 Kimberly Well', city='Juliemouth', state='Connecticut', zip=98624, lng=-122.601934, lat=24.2309255),
 Row(name='Nicholas Kelley', age=24, street='123 Monique Trail Suite 682', city='West Kelly', state='Missouri', zip=84052, lng=-140.279924, lat=-13.353849),
 Row(name='James Smith', age=25, street='61865 Samantha Station', city='East Amandafort', state='South Dakota', zip=27347, lng=145.547438, lat=0.703914),
 Row(name='Sheila Nolan', age=36, street='3391 Thomas Course Suite 266', city='West Evanton', state='Oklahoma', zip=82335, lng=-157.253466, lat=49.434396),
 Row(name='Destiny Davis', age=20, street='7883 Steele Ports Suite 434', city='New Jennifer', state='North Dakota', zip=67114, lng=-38.158574, lat=-52.067748),
 Row(name='Terri Choi', age=28, street='1267 Ruth Common Suite 944', city='Wilsonmouth', state='Alaska', zip=3444, lng=-1.785419, lat=-58.1137965),
 Row(name='Courtney Todd', age=20, street='50151 Stone Locks', city='Lake Jessica', state='Texas', zip=83448, lng=-146.418109, lat=64.184259),
 Row(name='Eddie Sheppard', age=26, street='102 Thomas Falls', city='Georgestad', state='Washington', zip=82357, lng=-34.679999, lat=-73.22125),
 Row(name='Juan Jackson', age=21, street='03505 Bradley Causeway Apt. 787', city='Lake Michaelview', state='Maryland', zip=56323, lng=-125.931124, lat=-53.8294485),
 Row(name='Theresa Brown', age=21, street='56723 Ingram Common Suite 608', city='South Adrian', state='Kansas', zip=88888, lng=6.880009, lat=19.091412),
 Row(name='Austin Mitchell', age=24, street='71185 Kimberly Fields Suite 847', city='East Alyssastad', state='Rhode Island', zip=24893, lng=-157.731507, lat=-37.1989575),
 Row(name='Calvin Perez', age=37, street='992 Kristen Stravenue', city='Clarkville', state='Minnesota', zip=14804, lng=-160.85983, lat=-11.0614485),
 Row(name='Dr. Christopher Howard', age=39, street='789 Kevin Center', city='East Jesus', state='Arizona', zip=50328, lng=-23.642438, lat=-69.043802),
 Row(name='Tracie Conner', age=32, street='8449 Michelle Inlet', city='Riverastad', state='Florida', zip=20596, lng=-12.336917, lat=-26.0470675),
 Row(name='Kimberly Hendricks', age=38, street='0537 Cameron Turnpike', city='Gardnerbury', state='Indiana', zip=24520, lng=-172.155566, lat=50.9278435),
 Row(name='Martin Mack', age=19, street='6814 West Tunnel', city='Gonzalezland', state='New York', zip=23886, lng=169.671128, lat=18.3474725),
 Row(name='Angela Rodriguez', age=38, street='827 Crystal Islands', city='Hillburgh', state='Iowa', zip=49931, lng=-36.92716, lat=79.2703205),
 Row(name='Sara Hart', age=33, street='7630 Monique Trail', city='New Sarah', state='Oregon', zip=39951, lng=-38.726417, lat=-52.2788505),
 Row(name='David Watson MD', age=37, street='1166 Andrea Street Suite 581', city='Daltonstad', state='Nebraska', zip=72963, lng=-88.008855, lat=-7.869147),
 Row(name='Krista Preston PhD', age=21, street='21807 Welch Rue Apt. 856', city='New Bonnie', state='Florida', zip=65904, lng=-60.957692, lat=8.0409075),

In [13]:
u40[0]#row

Row(name='Douglas Snyder', age=23, street='8307 Cindy Field Apt. 585', city='Ashleyberg', state='Iowa', zip=57094, lng=151.321619, lat=-7.13948)

In [14]:
u40[0].asDict()#dictionary

{'name': 'Douglas Snyder',
 'age': 23,
 'street': '8307 Cindy Field Apt. 585',
 'city': 'Ashleyberg',
 'state': 'Iowa',
 'zip': 57094,
 'lng': 151.321619,
 'lat': -7.13948}

In [15]:
u40[0].asDict()['name']

'Douglas Snyder'

In [16]:
for x in u40: # iterate the array 
 print(x.asDict())

{'name': 'Douglas Snyder', 'age': 23, 'street': '8307 Cindy Field Apt. 585', 'city': 'Ashleyberg', 'state': 'Iowa', 'zip': 57094, 'lng': 151.321619, 'lat': -7.13948}
{'name': 'Travis Davis', 'age': 25, 'street': '1496 Perez Junction', 'city': 'Lake Melinda', 'state': 'Utah', 'zip': 31874, 'lng': 129.198262, 'lat': -86.722102}
{'name': 'Colin Carter', 'age': 34, 'street': '534 Marshall Way', 'city': 'Port Calebbury', 'state': 'Maine', 'zip': 25208, 'lng': 46.737898, 'lat': 80.764342}
{'name': 'Kara Sandoval', 'age': 30, 'street': '831 Amber Crescent', 'city': 'Cynthiatown', 'state': 'South Carolina', 'zip': 65868, 'lng': 120.819117, 'lat': 45.1953135}
{'name': 'Eric Franklin', 'age': 33, 'street': '7118 Goodman Mall', 'city': 'North Kathleen', 'state': 'North Carolina', 'zip': 92272, 'lng': 93.319131, 'lat': -49.2371385}
{'name': 'Steven Bolton', 'age': 27, 'street': '6644 Brian Flat Suite 460', 'city': 'North Jeffreychester', 'state': 'North Carolina', 'zip': 69441, 'lng': -75.89488, 'lat': -38.8799715}
{'name': 'Jose Acosta', 'age': 34, 'street': '708 Tonya Forges Apt. 669', 'city': 'New Amanda', 'state': 'Wisconsin', 'zip': 84664, 'lng': 147.080022, 'lat': 71.8281255}
{'name': 'Mallory Newton', 'age': 38, 'street': '675 Rogers Road Suite 447', 'city': 'Shannonchester', 'state': 'Hawaii', 'zip': 10481, 'lng': -157.341507, 'lat': -88.335825}
{'name': 'Mr. Richard Moore', 'age': 39, 'street': '412 Fowler Islands', 'city': 'Christopherville', 'state': 'Vermont', 'zip': 22199, 'lng': -75.610711, 'lat': -39.8949425}
{'name': 'William Li', 'age': 30, 'street': '4431 Robert Rue Suite 911', 'city': 'Lanceberg', 'state': 'Alabama', 'zip': 14598, 'lng': -159.934529, 'lat': -46.5291295}
{'name': 'Karen Carpenter', 'age': 39, 'street': '102 Michelle Ports', 'city': 'New Mercedesmouth', 'state': 'Louisiana', 'zip': 15374, 'lng': -31.647568, 'lat': -63.178956}
{'name': 'Jacob Marsh', 'age': 29, 'street': '44972 Lawrence Cove', 'city': 'Bowmanmouth', 'state': 'Washington', 'zip': 27731, 'lng': 65.88709, 'lat': -54.608903}
{'name': 'John Parker', 'age': 33, 'street': '9979 Ronald Freeway Apt. 705', 'city': 'Lake Michael', 'state': 'New Mexico', 'zip': 49965, 'lng': 77.921187, 'lat': 17.5216885}
{'name': 'Kelly White', 'age': 34, 'street': '475 Kirk Lock Apt. 449', 'city': 'Port Richardville', 'state': 'Georgia', 'zip': 32450, 'lng': 97.258658, 'lat': -74.9886005}
{'name': 'Alexandra Mullins DDS', 'age': 32, 'street': '7330 Randall Island', 'city': 'Kaylashire', 'state': 'Georgia', 'zip': 46653, 'lng': 109.190572, 'lat': 11.748215}
{'name': 'Ms. Nicole Henderson', 'age': 36, 'street': '1500 Brittney Avenue Apt. 743', 'city': 'New Jesus', 'state': 'Missouri', 'zip': 2841, 'lng': -128.868462, 'lat': -75.9054695}
{'name': 'Richard Murray', 'age': 24, 'street': '023 Gomez Circle Suite 891', 'city': 'Codyton', 'state': 'Illinois', 'zip': 29510, 'lng': -48.65468, 'lat': 24.241075}
{'name': 'Stacy Wilson', 'age': 25, 'street': '2594 Gilmore Court Apt. 716', 'city': 'Donnaton', 'state': 'New Hampshire', 'zip': 52778, 'lng': -125.802769, 'lat': -66.120617}
{'name': 'Stephen Moore', 'age': 18, 'street': '062 Snyder Dale Apt. 396', 'city': 'Taylorshire', 'state': 'South Carolina', 'zip': 79283, 'lng': 121.001126, 'lat': 21.2042355}
{'name': 'Michael Palmer', 'age': 20, 'street': '05907 White Common Apt. 437', 'city': 'Port Megan', 'state': 'West Virginia', 'zip': 99181, 'lng': -98.107018, 'lat': -14.371527}
{'name': 'Alyssa Burgess', 'age': 28, 'street': '44467 Torres Ridge Apt. 767', 'city': 'Spencerburgh', 'state': 'Maryland', 'zip': 85793, 'lng': 105.219483, 'lat': 18.693497}
{'name': 'Ronald Green', 'age': 32, 'street': '15655 Hernandez Mill Suite 837', 'city': 'Port Phyllis', 'state': 'California', 'zip': 26342, 'lng': -160.527931, 'lat': 39.48574}
{'name': 'Jason Baker', 'age': 33, 'street': '9204 Kylie View Suite 653', 'city': 'Abigailburgh', 'state': 'Iowa', 'zip': 7917, 'lng': -142.496693, 'lat': -36.58947}
{'name': 'Margaret Griffith', 'age': 23, 'street': '69635 Palmer Trail Suite 465', 'city': 'Port Alyssa', 'state': 'Colorado', 'zip': 29424, 'lng': 115.167632, 'lat': 57.034145}
{'name': 'Brandon Valencia', 'age': 35, 'street': '5820 Tammy Track Suite 560', 'city': 'North Allison', 'state': 'Oklahoma', 'zip': 43571, 'lng': -158.450745, 'lat': -10.753513}
{'name': 'Mr. Adam Smith', 'age': 38, 'street': '299 Blankenship Land Apt. 345', 'city': 'Seanview', 'state': 'Montana', 'zip': 74018, 'lng': -53.624781, 'lat': -77.935335}
{'name': 'John Rodgers', 'age': 18, 'street': '3495 Gloria Ferry', 'city': 'Pattersonhaven', 'state': 'New Mexico', 'zip': 46820, 'lng': -32.488061, 'lat': 83.2514325}
{'name': 'Lee Donaldson', 'age': 23, 'street': '737 Micheal Junction', 'city': 'Susanmouth', 'state': 'Vermont', 'zip': 9211, 'lng': -14.178351, 'lat': -10.378729}
{'name': 'Robert Sharp', 'age': 34, 'street': '65205 Dennis Crescent Apt. 585', 'city': 'Lake Wendytown', 'state': 'Georgia', 'zip': 24348, 'lng': -74.568626, 'lat': 17.443412}
{'name': 'Cole Fletcher', 'age': 31, 'street': '96385 Diaz Underpass', 'city': 'Shieldston', 'state': 'North Carolina', 'zip': 98083, 'lng': -74.320038, 'lat': 55.7360175}
{'name': 'Nicholas Carlson', 'age': 29, 'street': '53642 Jacqueline Trail Suite 843', 'city': 'North Sandraburgh', 'state': 'North Dakota', 'zip': 21062, 'lng': 173.932076, 'lat': 55.0328045}
{'name': 'Jesse Mcgee', 'age': 26, 'street': '0266 Chan Street Suite 332', 'city': 'North Robert', 'state': 'Maryland', 'zip': 1640, 'lng': 117.483637, 'lat': 68.888271}
{'name': 'Melissa Clark', 'age': 34, 'street': '963 Huber Mountain Apt. 473', 'city': 'New Marytown', 'state': 'Nevada', 'zip': 57592, 'lng': 166.489018, 'lat': -59.325578}
{'name': 'Kimberly Martin', 'age': 20, 'street': '27881 Kenneth Locks', 'city': 'Orozcotown', 'state': 'Wisconsin', 'zip': 33665, 'lng': -31.494113, 'lat': 12.952741}
{'name': 'Jennifer Austin', 'age': 39, 'street': '2246 Klein Ports Suite 721', 'city': 'Trevorport', 'state': 'Arkansas', 'zip': 24865, 'lng': -73.040314, 'lat': 17.664625}
{'name': 'Mrs. Marissa Massey', 'age': 32, 'street': '84612 Pamela Extension', 'city': 'North Kelseyburgh', 'state': 'North Carolina', 'zip': 13310, 'lng': -77.854326, 'lat': 48.8903585}
{'name': 'Michelle Hernandez', 'age': 20, 'street': '9107 Carlos Fall Suite 838', 'city': 'Marioland', 'state': 'Virginia', 'zip': 23615, 'lng': -51.187402, 'lat': 7.6954185}
{'name': 'Charles Ramirez', 'age': 25, 'street': '9224 Vasquez Branch Apt. 766', 'city': 'New Scott', 'state': 'Kentucky', 'zip': 85964, 'lng': -69.383591, 'lat': 85.736318}
{'name': 'Jacqueline Tucker', 'age': 26, 'street': '9726 Castro Road', 'city': 'North Jenniferland', 'state': 'Rhode Island', 'zip': 86491, 'lng': 48.97366, 'lat': 7.4428555}
{'name': 'Vincent Woodard', 'age': 27, 'street': '063 Perkins Valley', 'city': 'West Joshua', 'state': 'Ohio', 'zip': 94391, 'lng': 124.887258, 'lat': -4.6209475}
{'name': 'Lisa Norman', 'age': 21, 'street': '46237 Christopher Rest', 'city': 'New Ralph', 'state': 'Tennessee', 'zip': 6051, 'lng': -87.514312, 'lat': -46.368582}
{'name': 'Anthony Johnson', 'age': 35, 'street': '2689 Pham Crest', 'city': 'Port Johnathan', 'state': 'South Carolina', 'zip': 37154, 'lng': 65.564821, 'lat': -30.556331}
{'name': 'Donna Mccullough', 'age': 18, 'street': '8004 Watson Shores Apt. 537', 'city': 'Joshuafurt', 'state': 'Hawaii', 'zip': 2350, 'lng': -171.521481, 'lat': 34.34947}
{'name': 'Rachel Mitchell', 'age': 26, 'street': '34878 Campbell Mission Apt. 541', 'city': 'East Michelle', 'state': 'Oklahoma', 'zip': 14410, 'lng': -65.802526, 'lat': 20.9933865}
{'name': 'Erica Houston DDS', 'age': 28, 'street': '79314 Todd Trace', 'city': 'South Joseph', 'state': 'California', 'zip': 14643, 'lng': -124.875787, 'lat': -24.3770745}
{'name': 'Daniel Erickson', 'age': 36, 'street': '628 Dawn Loop Apt. 327', 'city': 'Lake Rebeccatown', 'state': 'Wisconsin', 'zip': 67493, 'lng': 164.358257, 'lat': -13.256061}
{'name': 'Amber Hill DDS', 'age': 37, 'street': '26874 Shaffer River Apt. 548', 'city': 'South Marciamouth', 'state': 'Illinois', 'zip': 65406, 'lng': -67.917689, 'lat': 54.354821}
{'name': 'Andrea Bray', 'age': 18, 'street': '405 Michael Junction', 'city': 'Port Hollytown', 'state': 'Nebraska', 'zip': 37708, 'lng': -146.141492, 'lat': -71.2758245}
{'name': 'Kristen Rivera', 'age': 38, 'street': '763 Miller Bypass', 'city': 'North Tiffany', 'state': 'South Dakota', 'zip': 93706, 'lng': 172.739307, 'lat': -80.1932545}
{'name': 'Carol Perez', 'age': 30, 'street': '0443 Linda Village', 'city': 'Rossport', 'state': 'Missouri', 'zip': 16757, 'lng': -139.921034, 'lat': 53.237987}
{'name': 'David Moore', 'age': 19, 'street': '1469 Benjamin Mall', 'city': 'Tiffanyborough', 'state': 'Wyoming', 'zip': 23157, 'lng': -61.576129, 'lat': 11.5425515}
{'name': 'David Harrison', 'age': 36, 'street': '5175 Katherine Wells Apt. 635', 'city': 'North Curtischester', 'state': 'Alaska', 'zip': 93265, 'lng': -23.320422, 'lat': 72.2174435}
{'name': 'Frederick Evans', 'age': 33, 'street': '58368 Caleb Camp', 'city': 'Penningtonburgh', 'state': 'Louisiana', 'zip': 53793, 'lng': -173.223589, 'lat': 83.034729}
{'name': 'Denise Rush', 'age': 21, 'street': '122 Jones Islands Apt. 136', 'city': 'Amyton', 'state': 'Alaska', 'zip': 24856, 'lng': 173.722498, 'lat': -26.9038975}
{'name': 'Traci Gallagher', 'age': 20, 'street': '93101 Bennett Lake Apt. 438', 'city': 'New Ericashire', 'state': 'Arkansas', 'zip': 31040, 'lng': -118.69654, 'lat': 73.6021305}
{'name': 'Justin Page', 'age': 19, 'street': '7874 Sarah Manors Suite 460', 'city': 'New Peterside', 'state': 'California', 'zip': 24606, 'lng': -11.110459, 'lat': 52.4860345}
{'name': 'Arthur Stone', 'age': 18, 'street': '00411 Jones Island Apt. 757', 'city': 'West Sydney', 'state': 'West Virginia', 'zip': 51328, 'lng': 136.728678, 'lat': 83.680243}
{'name': 'Cindy Williams', 'age': 18, 'street': '617 Ross Shoal', 'city': 'Port Michael', 'state': 'Hawaii', 'zip': 64836, 'lng': 83.974455, 'lat': 87.5228595}
{'name': 'Larry Dunn', 'age': 30, 'street': '377 Shawn Well', 'city': 'Lake Kellyville', 'state': 'Texas', 'zip': 21402, 'lng': 64.215362, 'lat': -24.93869}
{'name': 'Richard Howell', 'age': 26, 'street': '7431 Victor Stream', 'city': 'Allisonbury', 'state': 'Alaska', 'zip': 23534, 'lng': -53.108344, 'lat': -69.0272895}
{'name': 'Stephen Owens', 'age': 39, 'street': '8515 Susan Lights Apt. 535', 'city': 'Jonathanmouth', 'state': 'New Mexico', 'zip': 8499, 'lng': 123.350351, 'lat': 45.8033095}
{'name': 'Emily Mccarthy', 'age': 20, 'street': '568 Kayla Centers', 'city': 'Port Edwardville', 'state': 'New Mexico', 'zip': 83038, 'lng': 141.295739, 'lat': 72.147992}
{'name': 'Jacqueline Hawkins', 'age': 33, 'street': '5857 Hood Lake Apt. 485', 'city': 'Lake Cynthia', 'state': 'Mississippi', 'zip': 38079, 'lng': 22.381065, 'lat': 56.43137}
{'name': 'David Solomon', 'age': 38, 'street': '869 Bradley Bypass Suite 753', 'city': 'Webbfort', 'state': 'Maryland', 'zip': 67278, 'lng': 52.976344, 'lat': 20.546445}
{'name': 'Mrs. Rebecca Rowe', 'age': 39, 'street': '067 Michaela Forks Apt. 197', 'city': 'Angelicaport', 'state': 'Michigan', 'zip': 83538, 'lng': -153.750449, 'lat': 69.866695}
{'name': 'David Thompson', 'age': 26, 'street': '159 Clay Fork', 'city': 'Richardston', 'state': 'Illinois', 'zip': 43916, 'lng': 45.284211, 'lat': 50.87704}
{'name': 'John Cole', 'age': 34, 'street': '16998 Jamie Keys', 'city': 'Port Stacy', 'state': 'Colorado', 'zip': 3433, 'lng': 155.816205, 'lat': -51.92454}
{'name': 'Cathy Thompson', 'age': 29, 'street': '9667 Potts Island', 'city': 'New David', 'state': 'Missouri', 'zip': 2381, 'lng': 80.516942, 'lat': 67.379554}
{'name': 'Sonya English', 'age': 34, 'street': '969 Kevin Circles Apt. 205', 'city': 'South Robert', 'state': 'Wisconsin', 'zip': 69758, 'lng': 124.837828, 'lat': -61.301577}
{'name': 'Bryan Perez', 'age': 34, 'street': '27873 Dana Greens', 'city': 'Bellbury', 'state': 'Oklahoma', 'zip': 72395, 'lng': 176.590107, 'lat': 26.8938065}
{'name': 'Jeremy Steele', 'age': 33, 'street': '590 Ricardo Island', 'city': 'Gallegosborough', 'state': 'West Virginia', 'zip': 95613, 'lng': 73.065022, 'lat': -60.9064405}
{'name': 'Mark Alexander', 'age': 23, 'street': '7036 Michelle Curve', 'city': 'Perryside', 'state': 'Massachusetts', 'zip': 81469, 'lng': -116.947192, 'lat': -4.943737}
{'name': 'Zachary Smith', 'age': 36, 'street': '55085 Victoria Parkway Suite 952', 'city': 'North Christopher', 'state': 'Alabama', 'zip': 41646, 'lng': 171.419597, 'lat': 74.2019395}
{'name': 'Shelly Arias', 'age': 29, 'street': '811 Emily Rapid Apt. 406', 'city': 'Nealstad', 'state': 'California', 'zip': 37873, 'lng': -140.776914, 'lat': -86.946908}
{'name': 'Juan Wood', 'age': 20, 'street': '6185 Ortiz Plains', 'city': 'South Melvinside', 'state': 'Alaska', 'zip': 13616, 'lng': 90.614015, 'lat': 74.3701815}
{'name': 'Susan Hansen', 'age': 26, 'street': '391 Carpenter Freeway Apt. 191', 'city': 'Collierfort', 'state': 'Tennessee', 'zip': 48700, 'lng': -104.567852, 'lat': -25.031846}
{'name': 'Marcus Fitzgerald', 'age': 39, 'street': '3262 Kim Lodge Suite 869', 'city': 'Derekberg', 'state': 'Vermont', 'zip': 18365, 'lng': 88.238182, 'lat': -67.1448145}
{'name': 'Brent Woodward', 'age': 23, 'street': '93383 Thomas Dam Apt. 542', 'city': 'Port Robertfort', 'state': 'Louisiana', 'zip': 9333, 'lng': 45.532305, 'lat': 78.2564305}
{'name': 'Perry Paul', 'age': 26, 'street': '87407 Ramos Creek', 'city': 'Molinabury', 'state': 'Montana', 'zip': 44713, 'lng': -34.865722, 'lat': 70.2174135}
{'name': 'James Guzman', 'age': 22, 'street': '63389 Mary Street Suite 143', 'city': 'Lambland', 'state': 'Maryland', 'zip': 85589, 'lng': -107.80104, 'lat': 46.662965}
{'name': 'Lawrence Abbott', 'age': 39, 'street': '835 Coleman Cape Suite 714', 'city': 'New Markland', 'state': 'Kentucky', 'zip': 59334, 'lng': 108.385342, 'lat': -10.970527}
{'name': 'James Barrett', 'age': 24, 'street': '6993 Timothy Drive', 'city': 'Wilsonberg', 'state': 'Florida', 'zip': 3823, 'lng': -166.90839, 'lat': -16.334232}
{'name': 'Alexandra Horne', 'age': 25, 'street': '479 Richardson Trace', 'city': 'Ryanfort', 'state': 'Connecticut', 'zip': 83665, 'lng': -41.436271, 'lat': -63.6067135}
{'name': 'Tina Cooper', 'age': 18, 'street': '38458 Patricia Way', 'city': 'Bradyville', 'state': 'Washington', 'zip': 42539, 'lng': -14.231671, 'lat': 32.180067}
{'name': 'Karina Boyd', 'age': 22, 'street': '84497 Paul Pine', 'city': 'East Andreaport', 'state': 'Colorado', 'zip': 66533, 'lng': -157.230803, 'lat': -11.5398545}
{'name': 'Kim Rogers', 'age': 26, 'street': '013 Evans Pine', 'city': 'Mitchellfort', 'state': 'Nevada', 'zip': 37860, 'lng': 91.765368, 'lat': 5.340507}
{'name': 'Katherine Schmidt', 'age': 30, 'street': '67745 Anthony Creek', 'city': 'Nataliehaven', 'state': 'Utah', 'zip': 36188, 'lng': -113.26994, 'lat': 23.8302845}
{'name': 'Richard Smith', 'age': 20, 'street': '217 Sabrina Track Apt. 403', 'city': 'Wolfeville', 'state': 'Iowa', 'zip': 50486, 'lng': -167.228525, 'lat': 46.4579265}
{'name': 'Robert Mccullough', 'age': 33, 'street': '2478 Rickey Union', 'city': 'Hermanport', 'state': 'Pennsylvania', 'zip': 14152, 'lng': 103.804379, 'lat': 56.1258335}
{'name': 'Michael Neal', 'age': 22, 'street': '9362 Megan Lakes Apt. 418', 'city': 'South Marilynland', 'state': 'Oklahoma', 'zip': 50168, 'lng': 111.584163, 'lat': 67.2212765}
{'name': 'Elizabeth Sanchez', 'age': 39, 'street': '099 Mendoza Mills', 'city': 'Riveraport', 'state': 'Wisconsin', 'zip': 96856, 'lng': -112.351885, 'lat': 8.937676}
{'name': 'Walter Greer', 'age': 37, 'street': '647 Ochoa Mission', 'city': 'Juliahaven', 'state': 'Delaware', 'zip': 11692, 'lng': -119.53241, 'lat': 26.915679}
{'name': 'Mercedes Jones', 'age': 27, 'street': '2297 Ronald Crescent Suite 276', 'city': 'Snyderchester', 'state': 'Oklahoma', 'zip': 12181, 'lng': -40.37932, 'lat': -58.4787745}
{'name': 'Thomas Thomas', 'age': 34, 'street': '69009 Adam Glen Apt. 737', 'city': 'Allisonside', 'state': 'New Jersey', 'zip': 53476, 'lng': -54.341757, 'lat': -35.3304985}
{'name': 'Mike Dixon', 'age': 39, 'street': '400 Jones Forest', 'city': 'Rogersview', 'state': 'Tennessee', 'zip': 69386, 'lng': 68.244285, 'lat': 85.38242}
{'name': 'Bethany Lee', 'age': 25, 'street': '559 Henderson Mill', 'city': 'West Chelseaton', 'state': 'Pennsylvania', 'zip': 88696, 'lng': -145.706621, 'lat': 7.5191705}
{'name': 'Carlos Delgado', 'age': 21, 'street': '04867 Debra Street', 'city': 'West Michaelport', 'state': 'Montana', 'zip': 8910, 'lng': -122.031591, 'lat': -36.7863435}
{'name': 'Rhonda Solis', 'age': 35, 'street': '942 Kevin River', 'city': 'Walkerport', 'state': 'Nevada', 'zip': 6147, 'lng': -101.42165, 'lat': 55.5016285}
{'name': 'Michael Jordan', 'age': 24, 'street': '095 Max Trail Suite 148', 'city': 'New Susan', 'state': 'West Virginia', 'zip': 91942, 'lng': 35.572501, 'lat': 67.857958}
{'name': 'Tonya Glenn', 'age': 32, 'street': '9286 Michael Pine', 'city': 'East Jeffreystad', 'state': 'Tennessee', 'zip': 90783, 'lng': -57.184689, 'lat': 87.3673585}
{'name': 'Kevin Miller', 'age': 22, 'street': '273 Russell Mountains', 'city': 'Port Heather', 'state': 'Hawaii', 'zip': 35951, 'lng': 109.519506, 'lat': 69.138615}
{'name': 'Adam Beard', 'age': 21, 'street': '172 Jessica Lake', 'city': 'Huberberg', 'state': 'Arizona', 'zip': 93042, 'lng': 120.247073, 'lat': 66.5133075}
{'name': 'Patrick Carpenter', 'age': 39, 'street': '235 Smith Tunnel Apt. 299', 'city': 'Davidbury', 'state': 'Arizona', 'zip': 38348, 'lng': 78.867817, 'lat': -79.825791}
{'name': 'William Baker', 'age': 36, 'street': '82108 Cruz Shores', 'city': 'South John', 'state': 'Pennsylvania', 'zip': 84689, 'lng': -58.233419, 'lat': -56.4814765}
{'name': 'Kristin Hughes', 'age': 28, 'street': '0890 Reed Greens', 'city': 'New Lisahaven', 'state': 'Nebraska', 'zip': 40363, 'lng': 172.682015, 'lat': 37.2529735}
{'name': 'Mary Flowers', 'age': 34, 'street': '4731 Cody Lodge Apt. 606', 'city': 'South David', 'state': 'Mississippi', 'zip': 14479, 'lng': -172.794529, 'lat': -73.2650515}
{'name': 'Linda Brown', 'age': 22, 'street': '866 Michael Crescent Apt. 954', 'city': 'Port Adamburgh', 'state': 'Idaho', 'zip': 38085, 'lng': 176.30213, 'lat': 45.03062}
{'name': 'Nichole Castro', 'age': 32, 'street': '549 Edwin Freeway Apt. 428', 'city': 'Lake Raymond', 'state': 'Pennsylvania', 'zip': 13092, 'lng': -27.34863, 'lat': -45.054988}
{'name': 'Leslie Dean', 'age': 35, 'street': '44704 Spencer Mountains Suite 552', 'city': 'Alanport', 'state': 'Kansas', 'zip': 99766, 'lng': 66.853626, 'lat': -84.06461}
{'name': 'Benjamin Navarro', 'age': 25, 'street': '8812 Matthew Summit Apt. 354', 'city': 'Barronfort', 'state': 'Nevada', 'zip': 30302, 'lng': -158.432998, 'lat': 35.821897}
{'name': 'Kathy Goodman', 'age': 33, 'street': '402 Jonathan Lakes Suite 362', 'city': 'Jacksonshire', 'state': 'Florida', 'zip': 28313, 'lng': -23.93757, 'lat': -35.6394615}
{'name': 'Chelsea Jensen', 'age': 22, 'street': '218 Kimberly Well', 'city': 'Juliemouth', 'state': 'Connecticut', 'zip': 98624, 'lng': -122.601934, 'lat': 24.2309255}
{'name': 'Nicholas Kelley', 'age': 24, 'street': '123 Monique Trail Suite 682', 'city': 'West Kelly', 'state': 'Missouri', 'zip': 84052, 'lng': -140.279924, 'lat': -13.353849}
{'name': 'James Smith', 'age': 25, 'street': '61865 Samantha Station', 'city': 'East Amandafort', 'state': 'South Dakota', 'zip': 27347, 'lng': 145.547438, 'lat': 0.703914}
{'name': 'Sheila Nolan', 'age': 36, 'street': '3391 Thomas Course Suite 266', 'city': 'West Evanton', 'state': 'Oklahoma', 'zip': 82335, 'lng': -157.253466, 'lat': 49.434396}
{'name': 'Destiny Davis', 'age': 20, 'street': '7883 Steele Ports Suite 434', 'city': 'New Jennifer', 'state': 'North Dakota', 'zip': 67114, 'lng': -38.158574, 'lat': -52.067748}

In [17]:
#filter through sql
df.createOrReplaceTempView('people')
df_over40=spark.sql('select * from people where age > 40')
df_over40.show()

+--------------------+---+--------------------+------------------+-------------+-----+-----------+-----------+
|                name|age|              street|              city|        state|  zip|        lng|        lat|
+--------------------+---+--------------------+------------------+-------------+-----+-----------+-----------+
|       Shirley Green| 51|503 Davis Tunnel ...|         Port Ruth|        Idaho|92155|  127.43576| -9.8076355|
|Christopher Williams| 50|1267 Mary Tunnel ...|        Port Shane|     Delaware|15896|    32.9033| -21.212263|
|         Vicki Brown| 75|94223 Patricia St...|      Schwartzside|       Oregon|64721|  62.898116| 34.7408695|
|        Rebecca Neal| 73|733 Allison Junct...|          Reedstad|         Utah|94289| 163.616939| 83.8663655|
|       Sharon Martin| 63|996 Lang Coves Ap...|     Patriciashire|         Ohio|21511|   3.364172|  88.578107|
|      Jessica Miller| 79|16608 Annette For...|South Brittneyberg|     Michigan|53181|   93.16961| -83.073968|
|      Gary Castaneda| 53|6293 Benjamin Sta...|         Rileyview|     Michigan|34612| 165.064741| -11.021106|
|        David Morrow| 71|       864 James Way|          Johnbury|      Vermont|94099|-123.138443|-10.2139805|
|       Nicole Ingram| 43|   2660 Kristy Ports|          Adamberg|     Nebraska|24941|  11.621987| 45.6564825|
|       Dennis Howard| 46|46360 Brittany Vi...|         Smithport| South Dakota|10691|-144.232309|  -0.824164|
|       Monica Bailey| 73|3269 Navarro Free...|       Cochranview|     Colorado| 2002|  25.765052| 10.7635385|
|   Christopher Avery| 70|86730 Brandon Hil...|       Rodneyburgh|       Alaska|74345|  21.859024|-29.2745815|
|          David Yang| 76|6244 Derek Drive ...|Christopherborough|       Alaska|25932|-151.171843| 25.7210435|
|         Donna Hurst| 56|9994 Li Rest Suit...|      North Amanda|New Hampshire|57792|  98.769559| -84.222205|
|       Richard Cowan| 41|30672 Chelsea Mou...|         Amandaton|New Hampshire|46514| -12.153082|   24.56146|
|  Mr. Richard Riddle| 48|      921 Mayo Trail|    Lake Sarahfort|       Oregon|18064|  23.835439| 59.6893555|
|       James Schmitt| 70|295 Williamson Va...|       Natalieview|West Virginia|64207|  93.145893| -82.966283|
|     Michelle Murphy| 52|3908 Courtney Harbor|          Hallfurt|      Alabama|73007|-106.406096|  -3.426361|
|      Courtney House| 50| 5091 Delacruz Ferry|          Loriside| Pennsylvania|97227|  62.709889| 43.5930485|
|          Lisa Singh| 60|92327 Chavez Cove...|   West Angelaport|  Mississippi|15148| 142.853969| 38.9487345|
+--------------------+---+--------------------+------------------+-------------+-----+-----------+-----------+
only showing top 20 rows

In [18]:
df_over40.describe('age').show()#get a basic summary

+-------+------------------+
|summary|               age|
+-------+------------------+
|  count|               627|
|   mean|59.526315789473685|
| stddev|11.629141248659243|
|    min|                41|
|    max|                80|
+-------+------------------+

In [19]:
df.groupBy('state').count().show()

+-------------+-----+
|        state|count|
+-------------+-----+
|         Utah|   15|
|       Hawaii|   23|
|    Minnesota|   22|
|         Ohio|   17|
|       Oregon|   23|
|     Arkansas|   25|
|        Texas|   22|
| North Dakota|   14|
| Pennsylvania|   23|
|  Connecticut|   17|
|      Vermont|   22|
|     Nebraska|   17|
|       Nevada|   23|
|   Washington|   15|
|     Illinois|   14|
|     Oklahoma|   24|
|     Delaware|   17|
|       Alaska|   26|
|   New Mexico|   17|
|West Virginia|   17|
+-------------+-----+
only showing top 20 rows

In [20]:
df.agg({'age':'mean'}).show()

+--------+
|avg(age)|
+--------+
|  48.195|
+--------+

In [23]:
import pyspark.sql.functions as f
df.select(f.collect_set(df['state'])).collect()
# Returns a Row of unique states which will be all 50.
df.select(f.countDistinct('state').alias('states')).show()

+------+
|states|
+------+
|    50|
+------+

In [28]:
#returns a single column named states with a single value of 50.
df.select(f.md5('street').alias('hash')).collect()

[Row(hash='519ca180adcd29cb2ad7785f6b431550'),
 Row(hash='887ab8994275e9d9802052a4651137ac'),
 Row(hash='45cba2e42e7d85fb24b1eb9d27028946'),
 Row(hash='05c10b9d22fae7bb23ba83d492d501ff'),
 Row(hash='ee0ddadde81392a49f98238ae1aa5052'),
 Row(hash='5fe5dca8977ad454611265cd390e8187'),
 Row(hash='b08970cbd696b90420762ef5896eb08a'),
 Row(hash='9aa9c005327c21e0e9cce2e2569a6b81'),
 Row(hash='cd9223d0a1d202f77d680bfecc067a69'),
 Row(hash='4c55c7b9c8a714553be4e088c70f7a3c'),
 Row(hash='d28970cd3f92a1b8263e5c77d90529bf'),
 Row(hash='09dcb550e2c2692055ffe47f095a7ccf'),
 Row(hash='27e69c0218f344f9b217afbddea86a75'),
 Row(hash='2fea65251462845d74ac844a5ac48d0a'),
 Row(hash='940e46fd9dc0aa3021d3f31b00b53730'),
 Row(hash='2ddf2b3b226cf92474eb04cda3a3fda1'),
 Row(hash='4dd262668b838b99056aaff3f7fb7c34'),
 Row(hash='abb3c9f7c4c769b42a2a92ebab71f503'),
 Row(hash='ec117c6dfa4c5c688cc80d311926372f'),
 Row(hash='76e2dbcf2ff200df78f91bde1b9ca808'),
 Row(hash='d6846efa5bbac9c86815c03836f740b5'),
 Row(hash='caae423be0dec1cdf35e8b5937963cec'),
 Row(hash='f1fe96c6b87fa0952e4cd5e7051327d2'),
 Row(hash='45ff463ae45d84161b592461b5669949'),
 Row(hash='4e93f8428a6d0764f8f029e94aa6d024'),
 Row(hash='993bf80affb1432f9537ecd02569f515'),
 Row(hash='dcabc4f71b5fc99e04e7ad144f2dc2ec'),
 Row(hash='ed3cf3bc96281ea7d0998018f0d06268'),
 Row(hash='f9055dfa1ebfc3ece31a7444c121e07e'),
 Row(hash='3a5fc95957dbaa849ef1723aa6df37f3'),
 Row(hash='f5b17682187c8d30496cf4dba171273b'),
 Row(hash='534833b8da747c53481caf78ef3571b1'),
 Row(hash='9c9f97136eaa6aaaece3167707b6167f'),
 Row(hash='b04fece3c7a26d3e7c3769089c5c4b82'),
 Row(hash='ab58b33b1f4397d8dcab3ecdb490bdcb'),
 Row(hash='dee9df0a85bee736fe9f48ab7d5d7885'),
 Row(hash='adcf6a5460c69fb057d16a8de4867954'),
 Row(hash='a4baa26d1060355200c432421e92f3a2'),
 Row(hash='bb83d44ec0541453596133686edf9d74'),
 Row(hash='d0989858272dfa5ee61e51d57090af27'),
 Row(hash='11a3c60acdae61ac4e9dc53008cc64e1'),
 Row(hash='65962d2ac6cc0da04530f357072763af'),
 Row(hash='53c771ecacdc22512ade8f7f43e556c5'),
 Row(hash='a75288ef81ac1b1ec2f3f59e621cde3e'),
 Row(hash='d2bc0e2aa3c037dfcae275f03d99d3b4'),
 Row(hash='282bb2c9c5057f4805d513233bb73364'),
 Row(hash='3f4fe9239668a045d6abe73a1e6c7c1b'),
 Row(hash='8f804a899a9eaf6650c1fd3f47f946e3'),
 Row(hash='d76689b6c99d22e599ef6e8cf9973fa0'),
 Row(hash='3032141533faf191eccfa333d37fa0e2'),
 Row(hash='ed870aa591f9d9bd4af87bab5d902d74'),
 Row(hash='2bb0c45b92bfea73f816557983248d04'),
 Row(hash='160dde7ee6503fc1391cba29e2abafbf'),
 Row(hash='0f07a428e11c333a7aaa485bdc95d748'),
 Row(hash='f10dede8af812ac6f598ec6ceb14ea69'),
 Row(hash='be60478fa6801fef920d0dcac9e06452'),
 Row(hash='04170b8b198267148b1c12f00355e72c'),
 Row(hash='f733e19f312af5ad008df37158ff61ef'),
 Row(hash='c8ddb19a2584fbb1991e48c296b3b90f'),
 Row(hash='dfcdd3e514ebcdef629f152f7b8f38df'),
 Row(hash='1a03fb64ae33f7bd38ea8a81fba31d33'),
 Row(hash='7e5a2fa05c699f6f7a20161c293a2fe7'),
 Row(hash='9b365dc5bd324c88c2d3bee7217676e0'),
 Row(hash='e569af9d38d2fc91c932940d3a0d39c0'),
 Row(hash='0b5ea2c549d617f3d4bdc45088d801b1'),
 Row(hash='b360a5f7c1ccf4535d523dca58671bbf'),
 Row(hash='78bae400468d7064faca69bd522c2d02'),
 Row(hash='cbebbb464b591017a1a543af2ecf8d77'),
 Row(hash='bb2c94fef81f757d67e29e7fc90c8b5c'),
 Row(hash='8904c946c29c8f397b29078325f9ca02'),
 Row(hash='3beba46595da9f34365d234a73edbd6d'),
 Row(hash='3586df03a0eb4da254e214d9908e5d0c'),
 Row(hash='6dde99ce1a4d0309173122eb31f43519'),
 Row(hash='dc2dc35bcb9aa70faf7a22cae0c30a3d'),
 Row(hash='d2a4e6f12bdd11089997f904bad465d1'),
 Row(hash='7be1c43f1ba36b03261c0974767c135c'),
 Row(hash='5e7479f918fa708c7d8cbcc12a3ca0bb'),
 Row(hash='b1649f3bbca9d09dee2a651507a13809'),
 Row(hash='d0c7acda922767b7fe2c1a7e59ba9008'),
 Row(hash='9f76f2eab32b976a3f1e2f4e5e9c3b72'),
 Row(hash='a4e8b016bc9006727d838cc09ce6ff49'),
 Row(hash='65ff9cb6ae4430099e247db37a9387a1'),
 Row(hash='3648c87dd3effbd3f6202a524628f0cb'),
 Row(hash='9c847588c2136331f7c51f88c29c206b'),
 Row(hash='b3d51ce68ded637d3d179ff8de20da3e'),
 Row(hash='ffa5761ef80124a70d06e6f77a75c067'),
 Row(hash='a4499667c88265924425273242668f1b'),
 Row(hash='9131d213aa1f4efb3ba0b9070f08020e'),
 Row(hash='3cbadffa134c2b9ae36419c52be66ab2'),
 Row(hash='f2f891ea56e4d811a1d76e52f3ad8174'),
 Row(hash='26d3b0de00c7d5f2d9d1b7f1960759a2'),
 Row(hash='b14a53cbf2207631ed54211c9b04d630'),
 Row(hash='8b08dd97bbe0f30858191ba2e4860529'),
 Row(hash='8566fdc52db9708a62d9895f4766092b'),
 Row(hash='5f63aab4195d0ac22322b014492b7c26'),
 Row(hash='418eee0104f9c72879932128c314bd2c'),
 Row(hash='5785ec641e573b7483ff3180a3c26172'),
 Row(hash='b24ac3a48b3cbfb3f62c83d74838d8d4'),
 Row(hash='a820b8fd3fdaa54d7154aae681aae2bb'),
 Row(hash='b6bf99a1c3e090e070152df1b9638ef8'),
 Row(hash='c7ecd6a6d1c307310c1018e5c7558f04'),
 Row(hash='7a025616ada547b16fb83961a0efbb9b'),
 Row(hash='9db8d08301d5718538aadbe39fc5676b'),
 Row(hash='48bbbe4b6c7f92e62c594547122e6e1e'),
 Row(hash='ec53f21fef3dee0c402db505558c925b'),
 Row(hash='8c2c486cb67ab623e3f8ffa0f1d04651'),
 Row(hash='bd02671ab8bc44cc12731fafb5a9d154'),
 Row(hash='877b9005f3f9374785629ed79fb36fb8'),
 Row(hash='dc446dbfea09b9da51251b8059a744b7'),
 Row(hash='3436890f87b60df4434257b53a58882e'),
 Row(hash='4add5bebdde5bff82f65addf01cd6fd5'),
 Row(hash='93abac48df85d5380aa77b65e64f7cd6'),
 Row(hash='2b6078ea8a0c1aa710cb5a79c35c810b'),
 Row(hash='769b6e7962db34ff8e1f3d3d8844244a'),
 Row(hash='a2bef942f99f5c5cb97ec06328e9be71'),
 Row(hash='4447b4b1c8859888e990ace1e13efb82'),
 Row(hash='949c1c3f63b63e42e2f2b3799252bc98'),
 Row(hash='37fa369d6ed67157388cbd85ccc13c78'),
 Row(hash='d28704bcb251e1565f2a5bf178d6bf5c'),
 Row(hash='c360bb304ee3aa1e79ed3a6caadaa399'),
 Row(hash='88e1155743c16df1ebb2974d0aed1e0a'),
 Row(hash='814ad153a11401b4aaf904b560b72750'),
 Row(hash='2e9d2b022917d672fdc5a54cd602c544'),
 Row(hash='dc08a110d7f083e9183f6f2a7c632283'),
 Row(hash='761ad62802cd963bb245e06d14bef5c8'),
 Row(hash='b2369799b0e691bfe404399e8fe861e8'),
 Row(hash='1cb63c412f996d83f57edcf6455eaf82'),
 Row(hash='b47eb4834ad5991774a10ef32ab3b29c'),
 Row(hash='e260fe304844b6031f7e33223486177c'),
 Row(hash='308a8b712926c538e871c770f54fe94f'),
 Row(hash='769e422a6af7b1e76981b64d94187a3f'),
 Row(hash='abd9e774e8cee2eb509521765ce31eb3'),
 Row(hash='5cb9f050fd72d3afaf262ffd31696fa4'),
 Row(hash='fbc85d6312063aafed0025b1c96e9951'),
 Row(hash='0aa2b40ee97f5f9afc7a2759d77a7907'),
 Row(hash='53860dcae44ca44c27643f947c9e5ca9'),
 Row(hash='83860aa0c63b6c2bc92a01661b618aa3'),
 Row(hash='e05f634253b6acc68a22475f79d32f0e'),
 Row(hash='8f2e3646c1bc52a6a0eec3e600736c69'),
 Row(hash='4f78b735633ee2f92ee8b8bfc3fed6d0'),
 Row(hash='2473d7e8073733182bb015ebe01eafe1'),
 Row(hash='891c5355f91edcbcfac3520654b3fe95'),
 Row(hash='11e826438112829450ff530752d0e618'),
 Row(hash='b576cf7ae394d27298d4a0d1fc1d36a2'),
 Row(hash='403c316ee39438122c693936e63d237e'),
 Row(hash='8b7bc971b3e44767a7d1dec389730fe2'),
 Row(hash='5638e39f46c61bc3f4bfbdd0f16b37c8'),
 Row(hash='f4d0233e670b869828eaf0b2f2bb0d5c'),
 Row(hash='f52ce68d6c46aeb3a77df1ebb511dc14'),
 Row(hash='e0349510c1e1aa9d16c4889ee5c281d0'),
 Row(hash='70dc3fe8338e72d5235210e8c7954e41'),
 Row(hash='7c50c28655ef851d3a72747996c209b1'),
 Row(hash='e532bd8f38abbbfb3876f3846992511e'),
 Row(hash='ec814c74cfdb05882edf98eab871e8f1'),
 Row(hash='6d428415b09a28f83b1904cf4664da66'),
 Row(hash='03bd54af2f964540c378df76a5478a66'),
 Row(hash='0de3b6868b1c5ecc062d1729b714d47f'),
 Row(hash='25b24c5e716da67604b1b36e836e061d'),
 Row(hash='123eec77eea1e22f7ef2f35ffdb746f6'),
 Row(hash='2022d653e6e55fa374f41b7c4ee74ca6'),
 Row(hash='2fc6a0ad396df7e2173329abe7f459de'),
 Row(hash='725d6e836903552c12e0dff9c5a5a21f'),
 Row(hash='bc01e8a395d3e7717ea762da6018cbf9'),
 Row(hash='8c6908c77c3c8f6d0bd5506730899b53'),
 Row(hash='56fa35d7ff44204b7eec2bec7be674e0'),
 Row(hash='f3cae56431a0a1458eb1d64e7313a549'),
 Row(hash='72eb6d455d52ad96d876cded102afa3d'),
 Row(hash='ffcdf76b95aa4648d69156665566918a'),
 Row(hash='76e6624d70151c7c0200a1a7c6fe78a7'),
 Row(hash='edd16b505e9e368395a26fcd4c24a18d'),
 Row(hash='4942be082ee8751acd8d19bb6914a440'),
 Row(hash='0cf170cb07968b4578f0afb0bb21d1a1'),
 Row(hash='55d3e0a92864f4c60bbf24ef290b7dc8'),
 Row(hash='d9bb45c0d9ba480ec6344548efe161be'),
 Row(hash='dafaf66ea85739b106fab66efeb2c110'),
 Row(hash='63a25548f2a7e767332ea3b2605569c7'),
 Row(hash='c0d414a5ca09995891c7786429c90dfa'),
 Row(hash='bf835266c84dad0c04e5475575ccc46a'),
 Row(hash='6688f073d07aa37d50d92c93eaca5e84'),
 Row(hash='8a44681d8adcab985bef0b015a296260'),
 Row(hash='1e5aa951335be445ce1425df1cc1e7f2'),
 Row(hash='6bd4c2fda59b1b46257400e50f24fe51'),
 Row(hash='c8404ff21e4a0faf4cba3ff1134f1d45'),
 Row(hash='7382adce9d8c2e7c1ef859da88ffcac7'),
 Row(hash='775daa5afd43600bbbf260c4eedce16f'),
 Row(hash='da61e3bb5e51841728a5062eba576ec5'),
 Row(hash='e0acfb13136329e8d7356612def3f1c2'),
 Row(hash='829884190c50369fb2a6983ccf589a84'),
 Row(hash='e4944a2e4904aa3e9f35302cd7cc0d91'),
 Row(hash='ca56852c5738c9666debaf8c17d4f1a9'),
 Row(hash='5500b3a6c6eea803460366ef5ac4606f'),
 Row(hash='36f2d1a7603b014b70c1b4103742c215'),
 Row(hash='9596f149f013a519073211aeb183771e'),
 Row(hash='7f9553c3ac007f71e4a570add269a913'),
 Row(hash='1cfbd74db34e780edd65622509aa4f67'),
 Row(hash='268bb3b38a41e397bf6c3e43bb3b0582'),
 Row(hash='6cffb0b928221e5958307ab908ccaea0'),
 Row(hash='b63d0794f1f4d1a80b5be1701ec5b7ee'),
 Row(hash='ebf8d1a2f8d557fb661bc4d667ee4ccf'),
 Row(hash='88ebeae64fcbbb9c0a9e865683eea9fe'),
 Row(hash='47ecd08e7c40c69f5bf03341b5dec4f1'),
 Row(hash='7dbe02dc9b4628108bc819fc26ec10db'),
 Row(hash='1c5838df8760e6a0cabd352782db80cb'),
 Row(hash='74fbb6ef5f7be7667de584cf17f3318c'),
 Row(hash='811496be6f1bea4d4894254e4a6f0263'),
 Row(hash='5a4379c8fbb23c520f7659a1e62357bc'),
 Row(hash='3de56aadf9c38d539fe2a42dcf19a372'),
 Row(hash='77f76f523dc1457f3eb9c8e3405fad2e'),
 Row(hash='75aa65a91b79afd964ae816f855e284e'),
 Row(hash='51108d2573c1d8ddd0520cfc1b5aa6d6'),
 Row(hash='6e3d2c3873b941435e37797f859e1b85'),
 Row(hash='ce3927403769252d8393a54490087fb0'),
 Row(hash='9e98ff1fc8f361262d01aeb0b50324fa'),
 Row(hash='4f1b0e2b45bb11a41054c8c38cee80c5'),
 Row(hash='6c7b1f542400267596e8dcd63ec1c2e1'),
 Row(hash='1c3df409f3354379c2acc3acf2c50923'),
 Row(hash='016561cecbe7f3a6ab6efe9b70e5f42d'),
 Row(hash='8807715fc132eb7f16ba403b756a2129'),
 Row(hash='3fe2f4ee85560516578c3e1ad8e2c0c6'),
 Row(hash='9868a93fe3d4eebff2b59ad929cdc0a3'),
 Row(hash='d2421913bf56c5fd7e10cdc43113fc6d'),
 Row(hash='117a52424d3c2277599252cb19431e05'),
 Row(hash='8d4be0cc8ce27ece3be82cb5918ff16e'),
 Row(hash='c4713674be4451c4e0929438f51940a6'),
 Row(hash='afcd71d8fb49fb58dd99992d45176e67'),
 Row(hash='2b3e185671e46834ced3036f3d5eedac'),
 Row(hash='566cb3a3a5bdcd5a005d50c8e4ecae51'),
 Row(hash='d7e692e4207f8a1feb5301cc62dde1d5'),
 Row(hash='64dc21611bd4e3211598d0662a0e3df4'),
 Row(hash='82fb9b71aac31fbdce91fcf71c3ed143'),
 Row(hash='577d535e3e5dd2f9f98d4fc3397a3588'),
 Row(hash='0d11f5900e9cb9660409a48fc1a5ffb3'),
 Row(hash='c392f0de5e837420cdb48e669f5824c0'),
 Row(hash='06549e7ae4022b04febbad8ce2160f4b'),
 Row(hash='8d8df684b1c551dd9ce884ff1ddfecc3'),
 Row(hash='aae4ced50853b80fcd527caf712eb44d'),
 Row(hash='a195b8e34ebd4538faf0c8a64e453081'),
 Row(hash='f565276f536162effa86e42860a0d607'),
 Row(hash='7443b447f917b4f1d858fe429366f35c'),
 Row(hash='e329a42615bccf06e1aa4d4017f33bc3'),
 Row(hash='f49bdc3252835c31f6c20fe99ececb10'),
 Row(hash='17dde116cf92dc969390e10e2abe5eee'),
 Row(hash='89418b76968f931d382e358c4e7e5a6d'),
 Row(hash='63cffca7ed459dca9ddbd747253bbf8e'),
 Row(hash='06c2790bfc8df639c4a44ceae9becc95'),
 Row(hash='58cc967901a4feb3dd280dabc42983fa'),
 Row(hash='da47816fa7385b3ebc296fb64330ac25'),
 Row(hash='a00e6cbb23e8ef9c29d560212d042f32'),
 Row(hash='ed66637feb7951bb44dafbf2c5b5192f'),
 Row(hash='232207308451962a8226e81b1c92a721'),
 Row(hash='34b5392cb35613057e229937ed19ea9a'),
 Row(hash='a08b5181090f739aabbe1acc9a0de197'),
 Row(hash='a6f8b27fb67aa1ebc2b759732f1c3134'),
 Row(hash='4838d10e5fe2ad1f582888502c51a513'),
 Row(hash='39fbd920a43e714723713eb9dba14e28'),
 Row(hash='2a244a1c71b3bb99d8dc0e95ed4e0c83'),
 Row(hash='69ef396550846f3dc29cd84616699fd0'),
 Row(hash='439ef7d58f02c4fab5392fe060304c4f'),
 Row(hash='96e001e7b64939bfe100cf1899df205e'),
 Row(hash='444ba63a541d3228a52df7676f1af43a'),
 Row(hash='6cb6b818f0d5cebc4be87ca99495ac10'),
 Row(hash='6453a6d858a832c5e1556b53d5db9708'),
 Row(hash='7d520854fa9e6d087015cd27499e80ca'),
 Row(hash='4ece82349b273ce3b41e61eecfd4b9d5'),
 Row(hash='7c5a05e5172c67db99526f9d75beab2f'),
 Row(hash='7ec04ad8c04b9d750b681640520e2d19'),
 Row(hash='6c81064c991531d9f14270f73a751e3f'),
 Row(hash='650fa2cb133d6c4ea0a85b8bdbc2a116'),
 Row(hash='6505ff7a78329e44fe00adbc89bd68b2'),
 Row(hash='c88f7efea02d362c23b3f23dbb745335'),
 Row(hash='2e9f9aa1348dd60980402def779bcb1e'),
 Row(hash='6d34818335d7d3cfd278c0c3bfc87851'),
 Row(hash='d8d41e8b1e37368734f61319da1becc3'),
 Row(hash='56aea8744a34b62200075f27cedbc74f'),
 Row(hash='d565c135e6dbc78aafc2c757406013f7'),
 Row(hash='4d446cacf2e6f1bf5979ddbeb65ea83b'),
 Row(hash='d5f9bb6e2b0e8ab8fcdbf96c21dcf76c'),
 Row(hash='7d8bd1ba769217ab337f4cbf61828d61'),
 Row(hash='9ade9896f7b8aa6aa5a1f3662cf3581a'),
 Row(hash='d01c840971a258157af49470b80b2808'),
 Row(hash='6798c290c9cfd783f9e7f029b282f738'),
 Row(hash='122a700487ba3c1f6315667c17ac80f3'),
 Row(hash='d84e50e340dc03a625900618c56f02c8'),
 Row(hash='2f73577e1633eb2ddc9b1ef4b5dd7974'),
 Row(hash='c74a9b498d548d76a4ba8e05a18b9134'),
 Row(hash='2a659731c2dc60ebc0deee4779adc759'),
 Row(hash='693f44f8f741f9c4d472fc1196ae86bc'),
 Row(hash='47aefe90ef019781c487851b8fa50935'),
 Row(hash='658556c6ef37c8238b91f5c78f4dd0ea'),
 Row(hash='14c33a8c11c9eeafb3c05ed3b59ad91b'),
 Row(hash='be027c572743caf62fe3c7aad184d467'),
 Row(hash='1cfdbcc2aa976bc4abdd9be08790215c'),
 Row(hash='9c89f424e0f3a8b1c54d3e1aa1aeb0e4'),
 Row(hash='6a170809815471ce89d587e62e7518dd'),
 Row(hash='47f63f93da34c2c8f0de88c337471ef7'),
 Row(hash='2cc400f3d872c0d4d7d71e36bc801ba1'),
 Row(hash='51bc1f58cba24c3fcb2690cf0fcc3f55'),
 Row(hash='81095e51482b7b59829ec44330378d13'),
 Row(hash='aed62ca686ff968cf13cb60edcd97b7c'),
 Row(hash='67d18664b7d6df58067ef8262a4f2ac6'),
 Row(hash='e5c7075981464d891eed4543e00535af'),
 Row(hash='fd399d2c9954e16a5bce17c1c83d43c7'),
 Row(hash='1ac723e460af24eb6be92728e8f0eea8'),
 Row(hash='8f9d53da651cde789cc2d8ace1725df3'),
 Row(hash='9d0c09c9b920860e0069501f22ffd2e2'),
 Row(hash='d5db8126824153d9e0fcfa4cfae8af23'),
 Row(hash='df2e8c336c0fe0342dfcc75ce2f68f23'),
 Row(hash='0b9995b1dff004c98a452409dc201dbe'),
 Row(hash='3bd793a80dad64bfdb2435890c44d934'),
 Row(hash='be461593ac9857c14688c1af77aff368'),
 Row(hash='77dd113d49da30bad142397c25879659'),
 Row(hash='7428d0838e305b475c3b750a14babb05'),
 Row(hash='617d1e453cfa3854734e122c05dcc2d1'),
 Row(hash='b08ef77233d7974ef37a6ce359ec618b'),
 Row(hash='aa50333529aad5535fffbb26dcea7dc2'),
 Row(hash='7120605f43c2d2e5e02b2153e6d16e80'),
 Row(hash='4e13b7613ed5d4922c1c417f81693a27'),
 Row(hash='a55a5846b95460ffcf36ed214e5414a0'),
 Row(hash='50a6da9637fadaf3d86597d40285a5fa'),
 Row(hash='5a39b409e282c526f90563e436408ead'),
 Row(hash='1c6f1d74309c546c4d935435404394da'),
 Row(hash='93340e742dcfdabe7bc5a73c3e659cbc'),
 Row(hash='19569092b073fb71fc10991503cac1fb'),
 Row(hash='2674729ca470484b4c90c24b1e0ade59'),
 Row(hash='65159c27b84bb6a792299a3f3c200549'),
 Row(hash='25982f0599ea280b0296b80d6ad6299f'),
 Row(hash='aa6c1d8f80318af456d8227d1407585f'),
 Row(hash='f5fc0d5510fede83ab85b6b34c728d2e'),
 Row(hash='c6b0633543a4f5d36476f3925011b7a8'),
 Row(hash='00e39788d8d23257cd8677b13091c7d4'),
 Row(hash='d11cbb60c15ff7c9d4d7a32109df80ea'),
 Row(hash='21185a28cb187499d0c53cdfe9a33b5b'),
 Row(hash='4a656fa7279f8fbf08b8c31e2bb0df4b'),
 Row(hash='4a9a89399db26b8ead05e794a567ad80'),
 Row(hash='06b3066d412523a77f826f76ef975809'),
 Row(hash='0e8545d0a32991c30da7ea7adc27b240'),
 Row(hash='34fee711a2cb4ada22f12a069813bb8b'),
 Row(hash='c6535777f3c4a05c3ca5cf5bf9ec05a3'),
 Row(hash='5aafabbd6af01a9d2c73978f594c65e9'),
 Row(hash='b1032db42de62b6142bc40a05b3feaaa'),
 Row(hash='e0d0cd9f1aaf99defc3e00d478e2388a'),
 Row(hash='8a91451ac809c36c10030a29c0c942fb'),
 Row(hash='abef12a43d6c5081fc6afe4d5c706de1'),
 Row(hash='0c2b6d79b2b2e92b67e0f88b4c1ffd58'),
 Row(hash='450e036e7a1ea6b685e11075fed2e480'),
 Row(hash='432308b321e7a1561354c4af7686ebc9'),
 Row(hash='911678e18be259759dd557c44cd1b0a5'),
 Row(hash='22cbbfc3b6b61f55c5f9d6e63da7f6fe'),
 Row(hash='e1fa3a9dea1faab702d176598126f8d2'),
 Row(hash='65be1d2be5c7ac17aaa1e43268389380'),
 Row(hash='9507eb138a7b204bbba64fec08630fc7'),
 Row(hash='ea823dce7a97213f5a6321936f7b1e2e'),
 Row(hash='a265dd076c2dd0a8edaa07b97df42190'),
 Row(hash='436414bfedda1ed5777535a549e393a0'),
 Row(hash='6435072fa72b8a3717bbf8c9781d5800'),
 Row(hash='4fe8216aa15b179512bb4d12165a8d26'),
 Row(hash='e85bdaded151ab4f98f83a0d065e38b3'),
 Row(hash='79a10fb021219f1ea3a65fe187ed7e25'),
 Row(hash='95c6a59defdcd7f4da5bbd83d78e1059'),
 Row(hash='1dc2b882f230269f6a961e19614a68e0'),
 Row(hash='83014af88ce6360cc894a53e0f006c69'),
 Row(hash='14abe23e20bc7ec81faa452058f84740'),
 Row(hash='4eb7101a3ce2525bb96bb4d440d00693'),
 Row(hash='87e92c193ae5974ed8703f96ffc22fa1'),
 Row(hash='11393bf3dd2b0995179cf8cfc4b10ed6'),
 Row(hash='4cf1998417f2e60bba418cbe62e388ab'),
 Row(hash='f21596abaca2dff8b416df59b2f684d7'),
 Row(hash='883c6a02a5b5a295cd570994aca1a413'),
 Row(hash='b95ebd75a086950ea71c7ea75646612e'),
 Row(hash='c349653ed069f40421469f5b0b606188'),
 Row(hash='685dd960bed21ae13377ad98656a7fd5'),
 Row(hash='fb3a91068d0cfbce0db98ddd709c990e'),
 Row(hash='883a46a77bd60d7a81e4896d6c3901df'),
 Row(hash='42a11470917f89a6aefd385ed1610c0d'),
 Row(hash='d26e3bdb4a6652575d0fde05d682bf14'),
 Row(hash='4eedbd3887bbf1d38ff57acdc3e342a1'),
 Row(hash='fbcc28681a7a6eaa4cfaf2e1e59bfe8a'),
 Row(hash='7456acc3ae1e25adc9be7f87173efce7'),
 Row(hash='7f7dc7459561265340e1a1ed0498b3b1'),
 Row(hash='9db1d50cf6f5ab6be9122981313b983d'),
 Row(hash='dba5a3dc91b5711a965ab212c1ece9c5'),
 Row(hash='bb6b8fb6e3694bd3162b946cee78bf26'),
 Row(hash='ac4f1201e9f2d3c8ba41f53f0b1df09a'),
 Row(hash='066ef55e04f7fd9b51e16807b5205687'),
 Row(hash='3297292db103bd9ccdc6ececbe10c063'),
 Row(hash='8d921fda259fd9354561d1b289aef0af'),
 Row(hash='24b9593966e932bb7b2ad2d1274ef1b6'),
 Row(hash='b5dc44246ac8447fb237d149afddfe10'),
 Row(hash='d7cd3d01da81b8dc1345f405ae522143'),
 Row(hash='c1137a1427da3cc147c0dd28a2200752'),
 Row(hash='66cfb532787c146e592158599181da79'),
 Row(hash='706db752946a102fdc9cdc27d037e375'),
 Row(hash='83a90e09e2bafa0ce180d8b9f087f9c8'),
 Row(hash='78a266b9520e588c26b44285701b8261'),
 Row(hash='ef370a192687aa66ffbf5deb7222f14a'),
 Row(hash='6cc77203074155184f8b65565e4827fa'),
 Row(hash='0c299c780d9332dc6fcdcdbff63c8ac9'),
 Row(hash='d3856634c8371307a52e62109bf84149'),
 Row(hash='0c5c622ef269501c4175416ab460678b'),
 Row(hash='65ebf07611c59b332df5ea8f41bdfb45'),
 Row(hash='ef268f39aff8f6bab049d5d0bb468bd1'),
 Row(hash='530d208045612ee8211b6b9d1ef6eabf'),
 Row(hash='a04ba7aef0544266749494e7cd5c3eb4'),
 Row(hash='7e4de59343e7a68631fc319de4fab0db'),
 Row(hash='57e9c536ed7550e8addb46b628e766d4'),
 Row(hash='212bf8649cc74a9598f69016a3fdd4d7'),
 Row(hash='fe81c71104489fb56dcf104565039a18'),
 Row(hash='fa3a5de79143b66e98d0d171c36f6abf'),
 Row(hash='3267bc0a74dafc36fe032195f23ee142'),
 Row(hash='ddfd1a3c36947abc4bc1c3ced39024e5'),
 Row(hash='d507ac42140161a75f3959b8e352ec78'),
 Row(hash='6736cabc17d44edeb2f43d36d5e21258'),
 Row(hash='dfb039d80e7851b4d5d24daf3bda587e'),
 Row(hash='7f7237192fc2deb0b480bcf76e7c50f7'),
 Row(hash='2530f1f889ec4162373ecc261853f7a8'),
 Row(hash='0dd11827e2b7038d11b03b5e689ac872'),
 Row(hash='4296b70977ac5be91b467dfa8dab9f49'),
 Row(hash='412e3e6259e5d3c5e99479c7471fd13c'),
 Row(hash='5072ded4e75064327216003abf03077a'),
 Row(hash='ab374e682a6fe86775c6522207e7a004'),
 Row(hash='ec0493ee227e51aacb6ce311dd7bfc53'),
 Row(hash='fe0f1aee738dd148211aaeda93a6ea44'),
 Row(hash='754a7336750e209a5b93322997f9a207'),
 Row(hash='295dcd8202f36389fce7e1642276c1f1'),
 Row(hash='9a3df7a168ca2856656928007d6001e3'),

In [33]:
df.select(f.reverse(df.state).alias('state-reverse')).collect()[3]

Row(state-reverse='awoI')

In [34]:
df.select(f.soundex(df.name).alias('soundex')).collect()

[Row(soundex='S642'),
 Row(soundex='C623'),
 Row(soundex='V216'),
 Row(soundex='D242'),
 Row(soundex='R125'),
 Row(soundex='S655'),
 Row(soundex='T612'),
 Row(soundex='J225'),
 Row(soundex='C452'),
 Row(soundex='G622'),
 Row(soundex='D135'),
 Row(soundex='K625'),
 Row(soundex='N245'),
 Row(soundex='E621'),
 Row(soundex='S315'),
 Row(soundex='D526'),
 Row(soundex='M521'),
 Row(soundex='C623'),
 Row(soundex='J222'),
 Row(soundex='D135'),
 Row(soundex='M465'),
 Row(soundex='D562'),
 Row(soundex='M662'),
 Row(soundex='R263'),
 Row(soundex='M662'),
 Row(soundex='W454'),
 Row(soundex='K652'),
 Row(soundex='J215'),
 Row(soundex='J563'),
 Row(soundex='J522'),
 Row(soundex='J516'),
 Row(soundex='M245'),
 Row(soundex='C635'),
 Row(soundex='K430'),
 Row(soundex='A425'),
 Row(soundex='L225'),
 Row(soundex='M621'),
 Row(soundex='C425'),
 Row(soundex='J221'),
 Row(soundex='E421'),
 Row(soundex='A164'),
 Row(soundex='K516'),
 Row(soundex='M252'),
 Row(soundex='R263'),
 Row(soundex='K623'),
 Row(soundex='C431'),
 Row(soundex='B653'),
 Row(soundex='J516'),
 Row(soundex='S324'),
 Row(soundex='A425'),
 Row(soundex='E452'),
 Row(soundex='A365'),
 Row(soundex='S315'),
 Row(soundex='S542'),
 Row(soundex='M241'),
 Row(soundex='J224'),
 Row(soundex='A421'),
 Row(soundex='S316'),
 Row(soundex='J215'),
 Row(soundex='N242'),
 Row(soundex='S652'),
 Row(soundex='R543'),
 Row(soundex='J251'),
 Row(soundex='A354'),
 Row(soundex='J221'),
 Row(soundex='J516'),
 Row(soundex='C342'),
 Row(soundex='S315'),
 Row(soundex='M634'),
 Row(soundex='G626'),
 Row(soundex='A516'),
 Row(soundex='M626'),
 Row(soundex='B653'),
 Row(soundex='T512'),
 Row(soundex='A553'),
 Row(soundex='D266'),
 Row(soundex='M635'),
 Row(soundex='Z265'),
 Row(soundex='J563'),
 Row(soundex='H366'),
 Row(soundex='L354'),
 Row(soundex='S315'),
 Row(soundex='R163'),
 Row(soundex='A536'),
 Row(soundex='T533'),
 Row(soundex='E622'),
 Row(soundex='C414'),
 Row(soundex='A531'),
 Row(soundex='N242'),
 Row(soundex='S416'),
 Row(soundex='M452'),
 Row(soundex='J252'),
 Row(soundex='M422'),
 Row(soundex='T526'),
 Row(soundex='L215'),
 Row(soundex='K516'),
 Row(soundex='J516'),
 Row(soundex='M625'),
 Row(soundex='M246'),
 Row(soundex='C642'),
 Row(soundex='J245'),
 Row(soundex='V236'),
 Row(soundex='V525'),
 Row(soundex='M246'),
 Row(soundex='L256'),
 Row(soundex='A535'),
 Row(soundex='D552'),
 Row(soundex='A535'),
 Row(soundex='A553'),
 Row(soundex='R163'),
 Row(soundex='W451'),
 Row(soundex='L655'),
 Row(soundex='T521'),
 Row(soundex='M652'),
 Row(soundex='R245'),
 Row(soundex='K325'),
 Row(soundex='D262'),
 Row(soundex='L655'),
 Row(soundex='C623'),
 Row(soundex='J552'),
 Row(soundex='G536'),
 Row(soundex='K155'),
 Row(soundex='D452'),
 Row(soundex='C535'),
 Row(soundex='M242'),
 Row(soundex='B652'),
 Row(soundex='T625'),
 Row(soundex='E622'),
 Row(soundex='J416'),
 Row(soundex='D546'),
 Row(soundex='A516'),
 Row(soundex='T532'),
 Row(soundex='A536'),
 Row(soundex='J453'),
 Row(soundex='T516'),
 Row(soundex='A536'),
 Row(soundex='K623'),
 Row(soundex='C641'),
 Row(soundex='E624'),
 Row(soundex='A422'),
 Row(soundex='A244'),
 Row(soundex='M222'),
 Row(soundex='R246'),
 Row(soundex='E542'),
 Row(soundex='D135'),
 Row(soundex='E421'),
 Row(soundex='E252'),
 Row(soundex='D136'),
 Row(soundex='F636'),
 Row(soundex='D526'),
 Row(soundex='W356'),
 Row(soundex='T622'),
 Row(soundex='J235'),
 Row(soundex='S316'),
 Row(soundex='A636'),
 Row(soundex='B540'),
 Row(soundex='C623'),
 Row(soundex='T622'),
 Row(soundex='G626'),
 Row(soundex='C534'),
 Row(soundex='L635'),
 Row(soundex='N244'),
 Row(soundex='K516'),
 Row(soundex='J516'),
 Row(soundex='D562'),
 Row(soundex='J256'),
 Row(soundex='K462'),
 Row(soundex='D545'),
 Row(soundex='R263'),
 Row(soundex='R163'),
 Row(soundex='C635'),
 Row(soundex='S315'),
 Row(soundex='K365'),
 Row(soundex='J455'),
 Row(soundex='S315'),
 Row(soundex='A535'),
 Row(soundex='E545'),
 Row(soundex='M665'),
 Row(soundex='C645'),
 Row(soundex='M252'),
 Row(soundex='R163'),
 Row(soundex='J535'),
 Row(soundex='S326'),
 Row(soundex='J245'),
 Row(soundex='J354'),
 Row(soundex='D521'),
 Row(soundex='W242'),
 Row(soundex='D132'),
 Row(soundex='R543'),
 Row(soundex='M626'),
 Row(soundex='D133'),
 Row(soundex='J255'),
 Row(soundex='V466'),
 Row(soundex='T326'),
 Row(soundex='S631'),
 Row(soundex='J524'),
 Row(soundex='J256'),
 Row(soundex='C623'),
 Row(soundex='J240'),
 Row(soundex='T462'),
 Row(soundex='T516'),
 Row(soundex='C335'),
 Row(soundex='S552'),
 Row(soundex='B651'),
 Row(soundex='J534'),
 Row(soundex='K415'),
 Row(soundex='J225'),
 Row(soundex='C645'),
 Row(soundex='S553'),
 Row(soundex='S535'),
 Row(soundex='J652'),
 Row(soundex='M624'),
 Row(soundex='S552'),
 Row(soundex='Z262'),
 Row(soundex='L632'),
 Row(soundex='S554'),
 Row(soundex='P542'),
 Row(soundex='D131'),
 Row(soundex='S315'),
 Row(soundex='S462'),
 Row(soundex='B653'),
 Row(soundex='J530'),
 Row(soundex='S255'),
 Row(soundex='E421'),
 Row(soundex='M241'),
 Row(soundex='P216'),
 Row(soundex='S663'),
 Row(soundex='M622'),
 Row(soundex='A242'),
 Row(soundex='K455'),
 Row(soundex='R163'),
 Row(soundex='B653'),
 Row(soundex='P614'),
 Row(soundex='J522'),
 Row(soundex='C325'),
 Row(soundex='S315'),
 Row(soundex='L652'),
 Row(soundex='C623'),
 Row(soundex='A524'),
 Row(soundex='R543'),
 Row(soundex='J521'),
 Row(soundex='K151'),
 Row(soundex='R225'),
 Row(soundex='M522'),
 Row(soundex='P543'),
 Row(soundex='A425'),
 Row(soundex='T522'),
 Row(soundex='T521'),
 Row(soundex='K651'),
 Row(soundex='J635'),
 Row(soundex='T532'),
 Row(soundex='K562'),
 Row(soundex='K365'),
 Row(soundex='R263'),
 Row(soundex='M242'),
 Row(soundex='E363'),
 Row(soundex='R163'),
 Row(soundex='J516'),
 Row(soundex='M245'),
 Row(soundex='E421'),
 Row(soundex='C623'),
 Row(soundex='M624'),
 Row(soundex='W436'),
 Row(soundex='M623'),
 Row(soundex='A235'),
 Row(soundex='T522'),
 Row(soundex='C623'),
 Row(soundex='T523'),
 Row(soundex='R532'),
 Row(soundex='G462'),
 Row(soundex='M232'),
 Row(soundex='M622'),
 Row(soundex='B354'),
 Row(soundex='K623'),
 Row(soundex='M625'),
 Row(soundex='A651'),
 Row(soundex='A352'),
 Row(soundex='S356'),
 Row(soundex='C642'),
 Row(soundex='S325'),
 Row(soundex='C642'),
 Row(soundex='S651'),
 Row(soundex='C623'),
 Row(soundex='R532'),
 Row(soundex='M242'),
 Row(soundex='T524'),
 Row(soundex='K155'),
 Row(soundex='S616'),
 Row(soundex='J516'),
 Row(soundex='M245'),
 Row(soundex='A351'),
 Row(soundex='P362'),
 Row(soundex='J536'),
 Row(soundex='S315'),
 Row(soundex='W451'),
 Row(soundex='K623'),
 Row(soundex='M614'),
 Row(soundex='L531'),
 Row(soundex='N242'),
 Row(soundex='B656'),
 Row(soundex='C536'),
 Row(soundex='J161'),
 Row(soundex='E622'),
 Row(soundex='C424'),
 Row(soundex='C635'),
 Row(soundex='G626'),
 Row(soundex='L243'),
 Row(soundex='B525'),
 Row(soundex='K323'),
 Row(soundex='C662'),
 Row(soundex='L635'),
 Row(soundex='C623'),
 Row(soundex='K421'),
 Row(soundex='J165'),
 Row(soundex='C422'),
 Row(soundex='J516'),
 Row(soundex='A364'),
 Row(soundex='N242'),
 Row(soundex='J522'),
 Row(soundex='T535'),
 Row(soundex='M622'),
 Row(soundex='W241'),
 Row(soundex='J253'),
 Row(soundex='R263'),
 Row(soundex='A164'),
 Row(soundex='S454'),
 Row(soundex='D235'),
 Row(soundex='Y453'),
 Row(soundex='F652'),
 Row(soundex='P362'),
 Row(soundex='C623'),
 Row(soundex='A524'),
 Row(soundex='T620'),
 Row(soundex='C635'),
 Row(soundex='C642'),
 Row(soundex='A352'),
 Row(soundex='S354'),
 Row(soundex='E321'),
 Row(soundex='C642'),
 Row(soundex='J522'),
 Row(soundex='B326'),
 Row(soundex='T621'),
 Row(soundex='A235'),
 Row(soundex='K516'),
 Row(soundex='S623'),
 Row(soundex='M244'),
 Row(soundex='C415'),
 Row(soundex='M244'),
 Row(soundex='A536'),
 Row(soundex='D626'),
 Row(soundex='S412'),
 Row(soundex='T622'),
 Row(soundex='C623'),
 Row(soundex='K516'),
 Row(soundex='M635'),
 Row(soundex='A524'),
 Row(soundex='A164'),
 Row(soundex='R246'),
 Row(soundex='M622'),
 Row(soundex='J161'),
 Row(soundex='N523'),
 Row(soundex='S663'),
 Row(soundex='S633'),
 Row(soundex='M242'),
 Row(soundex='A425'),
 Row(soundex='D133'),
 Row(soundex='K623'),
 Row(soundex='S554'),
 Row(soundex='C365'),
 Row(soundex='M636'),
 Row(soundex='A636'),
 Row(soundex='D136'),
 Row(soundex='C645'),
 Row(soundex='C532'),
 Row(soundex='M244'),
 Row(soundex='T524'),
 Row(soundex='D645'),
 Row(soundex='M634'),
 Row(soundex='L652'),
 Row(soundex='M246'),
 Row(soundex='A524'),
 Row(soundex='L652'),
 Row(soundex='R352'),
 Row(soundex='G626'),
 Row(soundex='S631'),
 Row(soundex='S252'),
 Row(soundex='S315'),
 Row(soundex='T524'),
 Row(soundex='J654'),
 Row(soundex='M241'),
 Row(soundex='K623'),
 Row(soundex='B616'),
 Row(soundex='T514'),
 Row(soundex='G153'),
 Row(soundex='M245'),
 Row(soundex='A524'),
 Row(soundex='C623'),
 Row(soundex='J535'),
 Row(soundex='V236'),
 Row(soundex='M253'),
 Row(soundex='P545'),
 Row(soundex='A553'),
 Row(soundex='K516'),
 Row(soundex='D543'),
 Row(soundex='J212'),
 Row(soundex='R521'),
 Row(soundex='E543'),
 Row(soundex='K152'),
 Row(soundex='R122'),
 Row(soundex='N325'),
 Row(soundex='G453'),
 Row(soundex='D554'),
 Row(soundex='R265'),
 Row(soundex='K425'),
 Row(soundex='M241'),
 Row(soundex='M526'),
 Row(soundex='B325'),
 Row(soundex='G550'),
 Row(soundex='M622'),
 Row(soundex='G552'),
 Row(soundex='S356'),
 Row(soundex='E621'),
 Row(soundex='B626'),
 Row(soundex='D524'),
 Row(soundex='L655'),
 Row(soundex='R241'),
 Row(soundex='M633'),
 Row(soundex='M625'),
 Row(soundex='R263'),
 Row(soundex='E421'),
 Row(soundex='A241'),
 Row(soundex='H636'),
 Row(soundex='R263'),
 Row(soundex='M422'),
 Row(soundex='L246'),
 Row(soundex='A422'),
 Row(soundex='M424'),
 Row(soundex='E363'),
 Row(soundex='M522'),
 Row(soundex='S315'),
 Row(soundex='R562'),
 Row(soundex='K463'),
 Row(soundex='S542'),
 Row(soundex='A545'),
 Row(soundex='K314'),
 Row(soundex='J256'),
 Row(soundex='M242'),
 Row(soundex='J440'),
 Row(soundex='T516'),
 Row(soundex='J162'),
 Row(soundex='L262'),
 Row(soundex='K341'),
 Row(soundex='J226'),
 Row(soundex='S542'),
 Row(soundex='W532'),
 Row(soundex='T523'),
 Row(soundex='R163'),
 Row(soundex='K665'),
 Row(soundex='E421'),
 Row(soundex='E542'),
 Row(soundex='A425'),
 Row(soundex='D645'),
 Row(soundex='C656'),
 Row(soundex='R553'),
 Row(soundex='R535'),
 Row(soundex='J456'),
 Row(soundex='J214'),
 Row(soundex='A525'),
 Row(soundex='M324'),
 Row(soundex='M243'),
 Row(soundex='M244'),
 Row(soundex='D242'),
 Row(soundex='K423'),
 Row(soundex='B530'),
 Row(soundex='D132'),
 Row(soundex='J211'),
 Row(soundex='M325'),
 Row(soundex='E622'),
 Row(soundex='A536'),
 Row(soundex='A535'),
 Row(soundex='J221'),
 Row(soundex='J425'),
 Row(soundex='P540'),
 Row(soundex='J524'),
 Row(soundex='L531'),
 Row(soundex='K152'),
 Row(soundex='L612'),
 Row(soundex='S255'),
 Row(soundex='D554'),
 Row(soundex='A553'),
 Row(soundex='S654'),
 Row(soundex='L254'),
 Row(soundex='S600'),
 Row(soundex='W436'),
 Row(soundex='N341'),
 Row(soundex='A365'),
 Row(soundex='R151'),
 Row(soundex='Y453'),
 Row(soundex='D623'),
 Row(soundex='R543'),
 Row(soundex='A235'),
 Row(soundex='K623'),
 Row(soundex='R563'),
 Row(soundex='W533'),
 Row(soundex='M665'),
 Row(soundex='C623'),
 Row(soundex='J516'),
 Row(soundex='T524'),
 Row(soundex='K516'),
 Row(soundex='J223'),
 Row(soundex='B422'),
 Row(soundex='S312'),
 Row(soundex='K345'),
 Row(soundex='M425'),
 Row(soundex='J525'),
 Row(soundex='M622'),
 Row(soundex='J451'),
 Row(soundex='A536'),
 Row(soundex='K423'),
 Row(soundex='M242'),
 Row(soundex='T622'),
 Row(soundex='M622'),
 Row(soundex='R531'),
 Row(soundex='L213'),
 Row(soundex='D451'),
 Row(soundex='D625'),
 Row(soundex='J524'),
 Row(soundex='M246'),
 Row(soundex='B140'),
 Row(soundex='M625'),
 Row(soundex='J162'),
 Row(soundex='A124'),
 Row(soundex='D542'),
 Row(soundex='R243'),
 Row(soundex='A424'),
 Row(soundex='B656'),
 Row(soundex='A421'),
 Row(soundex='M421'),
 Row(soundex='M244'),
 Row(soundex='J516'),
 Row(soundex='J652'),
 Row(soundex='J531'),
 Row(soundex='L623'),
 Row(soundex='A536'),
 Row(soundex='A425'),
 Row(soundex='A535'),
 Row(soundex='K623'),
 Row(soundex='M425'),
 Row(soundex='D541'),
 Row(soundex='C645'),
 Row(soundex='G626'),
 Row(soundex='C514'),
 Row(soundex='A425'),
 Row(soundex='D136'),
 Row(soundex='E421'),
 Row(soundex='A352'),
 Row(soundex='J211'),
 Row(soundex='P362'),
 Row(soundex='R246'),
 Row(soundex='J430'),
 Row(soundex='K516'),
 Row(soundex='K652'),
 Row(soundex='S251'),
 Row(soundex='J516'),
 Row(soundex='M623'),
 Row(soundex='M425'),
 Row(soundex='D135'),
 Row(soundex='M616'),
 Row(soundex='M523'),
 Row(soundex='P556'),
 Row(soundex='C565'),
 Row(soundex='M242'),
 Row(soundex='L652'),
 Row(soundex='V465'),
 Row(soundex='T524'),
 Row(soundex='C623'),
 Row(soundex='E625'),
 Row(soundex='J316'),
 Row(soundex='M635'),
 Row(soundex='P424'),
 Row(soundex='D541'),
 Row(soundex='P362'),
 Row(soundex='A536'),
 Row(soundex='J632'),
 Row(soundex='J660'),
 Row(soundex='W454'),
 Row(soundex='G626'),
 Row(soundex='D136'),
 Row(soundex='J535'),
 Row(soundex='M241'),
 Row(soundex='N242'),
 Row(soundex='S315'),
 Row(soundex='M252'),
 Row(soundex='S525'),
 Row(soundex='S525'),
 Row(soundex='M642'),
 Row(soundex='M633'),
 Row(soundex='D516'),
 Row(soundex='R525'),
 Row(soundex='D524'),
 Row(soundex='K153'),
 Row(soundex='G623'),
 Row(soundex='J165'),
 Row(soundex='P416'),
 Row(soundex='S345'),
 Row(soundex='C623'),
 Row(soundex='M663'),
 Row(soundex='J553'),
 Row(soundex='C623'),
 Row(soundex='B635'),
 Row(soundex='J235'),
 Row(soundex='A355'),
 Row(soundex='J561'),
 Row(soundex='J212'),
 Row(soundex='J535'),
 Row(soundex='V652'),
 Row(soundex='E543'),
 Row(soundex='D626'),
 Row(soundex='M345'),
 Row(soundex='J535'),
 Row(soundex='E421'),
 Row(soundex='C623'),
 Row(soundex='E352'),
 Row(soundex='A164'),
 Row(soundex='T461'),
 Row(soundex='A524'),
 Row(soundex='S252'),
 Row(soundex='C623'),
 Row(soundex='J234'),
 Row(soundex='M624'),
 Row(soundex='W455'),
 Row(soundex='S313'),
 Row(soundex='B653'),
 Row(soundex='S552'),
 Row(soundex='G164'),
 Row(soundex='J626'),
 Row(soundex='A352'),
 Row(soundex='D616'),
 Row(soundex='L532'),
 Row(soundex='B525'),
 Row(soundex='J414'),
 Row(soundex='G151'),
 Row(soundex='D235'),
 Row(soundex='R263'),
 Row(soundex='E355'),
 Row(soundex='B652'),
 Row(soundex='G632'),
 Row(soundex='T464'),
 Row(soundex='L256'),
 Row(soundex='E363'),
 Row(soundex='M242'),
 Row(soundex='D235'),
 Row(soundex='D512'),
 Row(soundex='J525'),
 Row(soundex='A425'),
 Row(soundex='J215'),
 Row(soundex='A554'),
 Row(soundex='E625'),
 Row(soundex='J252'),
 Row(soundex='M623'),
 Row(soundex='S532'),
 Row(soundex='C363'),
 Row(soundex='W436'),
 Row(soundex='T612'),
 Row(soundex='J561'),
 Row(soundex='D453'),
 Row(soundex='S536'),
 Row(soundex='J532'),
 Row(soundex='J521'),
 Row(soundex='A552'),
 Row(soundex='J254'),
 Row(soundex='N242'),
 Row(soundex='L531'),
 Row(soundex='J516'),
 Row(soundex='T531'),
 Row(soundex='T621'),
 Row(soundex='S536'),
 Row(soundex='J235'),
 Row(soundex='T152'),
 Row(soundex='M614'),
 Row(soundex='M615'),
 Row(soundex='J525'),
 Row(soundex='C645'),
 Row(soundex='P425'),
 Row(soundex='J452'),
 Row(soundex='B653'),
 Row(soundex='A452'),
 Row(soundex='M245'),
 Row(soundex='D242'),
 Row(soundex='T155'),
 Row(soundex='D623'),
 Row(soundex='C645'),
 Row(soundex='A532'),
 Row(soundex='J425'),
 Row(soundex='J535'),
 Row(soundex='C623'),
 Row(soundex='D552'),
 Row(soundex='M241'),
 Row(soundex='A524'),
 Row(soundex='C253'),
 Row(soundex='E543'),
 Row(soundex='C623'),
 Row(soundex='S553'),
 Row(soundex='J553'),
 Row(soundex='E362'),
 Row(soundex='T613'),
 Row(soundex='V525'),
 Row(soundex='D132'),
 Row(soundex='J215'),
 Row(soundex='M242'),
 Row(soundex='A536'),
 Row(soundex='J165'),
 Row(soundex='R543'),
 Row(soundex='K421'),
 Row(soundex='T554'),
 Row(soundex='S556'),
 Row(soundex='O261'),
 Row(soundex='C623'),
 Row(soundex='A636'),
 Row(soundex='B654'),
 Row(soundex='K155'),
 Row(soundex='E421'),
 Row(soundex='E622'),
 Row(soundex='T566'),
 Row(soundex='K516'),
 Row(soundex='D162'),
 Row(soundex='S322'),
 Row(soundex='R534'),
 Row(soundex='J553'),
 Row(soundex='C565'),
 Row(soundex='M633'),
 Row(soundex='T662'),
 Row(soundex='A422'),
 Row(soundex='R163'),
 Row(soundex='D162'),
 Row(soundex='D552'),
 Row(soundex='D542'),
 Row(soundex='P454'),
 Row(soundex='P362'),
 Row(soundex='D131'),
 Row(soundex='A516'),
 Row(soundex='J535'),
 Row(soundex='N354'),
 Row(soundex='T522'),
 Row(soundex='H362'),
 Row(soundex='E652'),
 Row(soundex='J232'),
 Row(soundex='S526'),
 Row(soundex='R163'),
 Row(soundex='A516'),
 Row(soundex='N354'),
 Row(soundex='J212'),
 Row(soundex='A536'),
 Row(soundex='K365'),
 Row(soundex='A242'),
 Row(soundex='R163'),
 Row(soundex='S553'),
 Row(soundex='T534'),
 Row(soundex='E253'),
 Row(soundex='A425'),
 Row(soundex='E622'),
 Row(soundex='R263'),
 Row(soundex='D542'),
 Row(soundex='D552'),
 Row(soundex='C655'),
 Row(soundex='B653'),
 Row(soundex='E546'),
 Row(soundex='L616'),
 Row(soundex='E656'),
 Row(soundex='D556'),
 Row(soundex='D545'),
 Row(soundex='R263'),
 Row(soundex='B623'),
 Row(soundex='T523'),
 Row(soundex='J245'),
 Row(soundex='B634'),
 Row(soundex='R514'),
 Row(soundex='D454'),
 Row(soundex='W455'),
 Row(soundex='R263'),
 Row(soundex='T526'),
 Row(soundex='J215'),
 Row(soundex='S545'),
 Row(soundex='N241'),
 Row(soundex='S315'),
 Row(soundex='I214'),
 Row(soundex='K365'),
 Row(soundex='T661'),
 Row(soundex='E623'),
 Row(soundex='M242'),
 Row(soundex='Z263'),
 Row(soundex='R352'),
 Row(soundex='T625'),
 Row(soundex='M453'),
 Row(soundex='J521'),
 Row(soundex='M243'),
 Row(soundex='B156'),
 Row(soundex='K414'),
 Row(soundex='R122'),
 Row(soundex='R121'),
 Row(soundex='B654'),
 Row(soundex='K341'),
 Row(soundex='S552'),
 Row(soundex='P362'),
 Row(soundex='P362'),
 Row(soundex='K535'),
 Row(soundex='D543'),
 Row(soundex='C623'),
 Row(soundex='L616'),
 Row(soundex='M546'),
 Row(soundex='S653'),
 Row(soundex='C642'),
 Row(soundex='S322'),
 Row(soundex='M534'),
 Row(soundex='R545'),
 Row(soundex='M345'),
 Row(soundex='C644'),
 Row(soundex='T563'),
 Row(soundex='J516'),
 Row(soundex='M241'),
 Row(soundex='J253'),
 Row(soundex='L332'),
 Row(soundex='P362'),
 Row(soundex='R216'),
 Row(soundex='M346'),
 Row(soundex='J162'),
 Row(soundex='E622'),
 Row(soundex='D542'),
 Row(soundex='C365'),
 Row(soundex='S252'),
 Row(soundex='C322'),
 Row(soundex='V236'),
 Row(soundex='C645'),
 Row(soundex='S525'),
 Row(soundex='D525'),
 Row(soundex='P623'),
 Row(soundex='M245'),
 Row(soundex='A423'),
 Row(soundex='R565'),
 Row(soundex='B525'),
 Row(soundex='W436'),
 Row(soundex='A354'),
 Row(soundex='S251'),
 Row(soundex='C623'),
 Row(soundex='C642'),
 Row(soundex='W351'),
 Row(soundex='L656'),
 Row(soundex='R532'),
 Row(soundex='A124'),
 Row(soundex='C565'),
 Row(soundex='N242'),
 Row(soundex='W532'),
 Row(soundex='S315'),
 Row(soundex='L615'),
 Row(soundex='D131'),
 Row(soundex='C643'),
 Row(soundex='B616'),
 Row(soundex='L653'),
 Row(soundex='J166'),
 Row(soundex='T466'),
 Row(soundex='D165'),
 Row(soundex='L225'),
 Row(soundex='A425'),
 Row(soundex='T516'),
 Row(soundex='J414'),
 Row(soundex='M622'),
 Row(soundex='G451'),
 Row(soundex='C642'),
 Row(soundex='T545'),
 Row(soundex='S536'),
 Row(soundex='S654'),
 Row(soundex='R554'),
 Row(soundex='C645'),
 Row(soundex='A524'),
 Row(soundex='T640'),
 Row(soundex='K426'),
 Row(soundex='B653'),
 Row(soundex='J212'),
 Row(soundex='D623'),
 Row(soundex='E624'),
 Row(soundex='A556'),
 Row(soundex='C365'),
 Row(soundex='S251'),
 Row(soundex='M325'),
 Row(soundex='J426'),
 Row(soundex='D543'),
 Row(soundex='S641'),
 Row(soundex='C623'),
 Row(soundex='R263'),
 Row(soundex='J521'),
 Row(soundex='J221'),
 Row(soundex='M623'),
 Row(soundex='R163'),
 Row(soundex='J651'),
 Row(soundex='M622'),
 Row(soundex='K652'),
 Row(soundex='P453'),
 Row(soundex='K652'),
 Row(soundex='E421'),
 Row(soundex='S635'),
 Row(soundex='M625'),
 Row(soundex='K656'),
 Row(soundex='H326'),
 Row(soundex='C424'),
 Row(soundex='J516'),
 Row(soundex='D623'),
 Row(soundex='K623'),
 Row(soundex='T652'),
 Row(soundex='D526'),

In [35]:
spark.stop()